<!DOCTYPE html>
<html>
<head>
<title>FoodTinder</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<link rel="stylesheet" href="style.css">
<link href="https://fonts.googleapis.com/css2?family=Kalam:wght@700&display=swap" rel="stylesheet">
<script>
var listStarted = false;
var currentItem = "";

</script>
</head>
<script>
function newCard(){
let foods = ['Baked Italian sandwiches','Baked ziti', 'BBQ chicken salad', 'Beef & broccoli', 'Beef or pork tenderloin', 'BLT', 'Bolognese sauce and pasta', 'Bowtie pasta & vegetables', 'Breaded chicken', 'Burgers or hotdogs', 'Burritos', 'Cafe Rio pork salads or burritos', 'Calzones', 'Cheeseburger soup', 'Cheesy bacon chicken', 'Chicken and broccoli casserole', 'Chicken and rice', 'Chicken cordon bleu', 'Chicken enchiladatortilla soup', 'Chicken fingers', 'Chicken noodle soup', 'Chicken nuggets', 'Chicken parmesan', 'Chicken pot pie', 'Chicken wings', 'Chimichangas', 'Cilantro-lime chicken', 'Clam chowder', 'Club salad ', 'Corn chowder', 'Crab cakes', 'Creamy potato soup', 'Crockpot Alfredo lasagna', 'Crockpot salsa chicken', 'Dijon chicken', 'Dr Pepper pulled pork sandwiches', 'Egg rolls', 'Eggplant parmesan', 'Enchiladas', 'Fajitas', 'Fettuccine Alfredo', 'Fish n chips', 'Fish sticks', 'Fish tacos', 'French bread pizza', 'French dip sandwiches', 'French onion soup', 'Fried chicken', 'Grilled cheese sandwiches', 'Grilled chicken', 'Ham', 'Hard tacos or tostadas', 'Homemade corn dogs', 'Homemade mac n cheese', 'Homemade pizza', 'Huevos rancheros', 'Italian wedding soup', 'Jambalaya', 'Kabobs', 'KFC bowls', 'Lasagna', 'Lasagna rolls', 'Lemon chicken ', 'Manicotti', 'Meatball subs', 'Meatballs and rice', 'Meatloaf', 'Mexican chicken sandwiches', 'Minestrone soup', 'Orange chicken', 'Pad Thai', 'Paninis', 'Pesto pasta', 'Pork chops', 'Pot roast', 'Pulled BBQ chicken', 'Quesadillas', 'Ribs', 'Rotini bake', 'Salmon', 'Salmon patties', 'Sausage & pepper pasta', 'Shepherds pie', 'Sloppy Joes', 'Smoked salmon bagel', 'Spaghetti and meatballs', 'Spinach-bacon mac N cheese', 'Steak', 'Stir fry', 'Stroganoff (chicken or beef)', 'Stuffed green peppers', 'Stuffed pasta shells', 'Stuffed pork chops', 'Taco salad', 'Taco soup', 'Tomato bisque', 'Tomato-bacon pasta', 'Tortellini', 'Tortellini soup', 'Tostadas', 'Twice-baked potatoes', 'Vegetable lasagna', 'White chicken chili'];
foods.push('Drip Coffee');
foods.push('Steeped Coffee');
foods.push('Vacuum-Method Coffee');
foods.push('Percolated Coffee');
foods.push('Coffee In Quantity');
foods.push('Cold-Brew Coffee');
foods.push('Iced Coffee');
foods.push('Vietnamese Coffee');
foods.push('Cuban Coffee');
foods.push('Frozen Coffee');
foods.push('Cold-Brewed Tea');
foods.push('Masala Chai');
foods.push('Iced Tea');
foods.push('Sweet Southern Iced Tea');
foods.push('Thai Iced Tea');
foods.push('Hot Cocoa');
foods.push('Cocoa Syrup');
foods.push('Quick Hot Cocoa');
foods.push('Ganache For Hot Chocolate');
foods.push('Quick Hot Chocolate Or Drinking Chocolate');
foods.push('Spiced Hot Cocoa');
foods.push('Spiced Hot Chocolate');
foods.push('Champurrado (Masa-Thickened Hot Chocolate)');
foods.push('Mayan Hot Chocolate');
foods.push('Brazilian Chocolate');
foods.push('Kai');
foods.push('Egg Cream');
foods.push('Tomato-Vegetable Juice');
foods.push('Citrus Juice Medley');
foods.push('Cranberry Juice');
foods.push('Tomato-Celery-Carrot Juice');
foods.push('Pineapple-Mango Juice');
foods.push('Carrot-Beet-Ginger Juice');
foods.push('Kale-Ginger Lemonade');
foods.push('Fruit Smoothie');
foods.push('Green Smoothie');
foods.push('Chocolate-Cherry Smoothie');
foods.push('Peanut Butter And Banana Smoothie');
foods.push('Papaya-Mango Batido');
foods.push('Mango Lassi');
foods.push('Fruit Kefir');
foods.push('Ice Cream Float');
foods.push('Milk Shake');
foods.push('Fruit Milk Shake');
foods.push('Vietnamese Avocado Shake');
foods.push('Lemonade Or Limeade');
foods.push('Flavored Or Italian Sodas');
foods.push('Fruit Sodas');
foods.push('Agua Fresca');
foods.push('Horchata');
foods.push('Panakam');
foods.push('Spicy Ginger Ale');
foods.push('Switchel');
foods.push('Watermelon Punch');
foods.push('Cranberry-Mango Punch');
foods.push('Pineapple Punch');
foods.push('Fruit Punch');
foods.push('Simple Syrup (Sugar Syrup)');
foods.push('Fruit Syrup');
foods.push('Citrus Syrup');
foods.push('Herb Syrup');
foods.push('Spiced Syrup');
foods.push('Grenadine');
foods.push('Fruit Shrub');
foods.push('Martini');
foods.push('Irma’S Gin And Juice');
foods.push('Gin And Tonic');
foods.push('The Last Word');
foods.push('Bronx');
foods.push('Gimlet');
foods.push('Gin Fizz');
foods.push('Tom Collins');
foods.push('Singapore Sling');
foods.push('Chan Chan');
foods.push('Negroni');
foods.push('Clover Club');
foods.push('Pimm’S Cup');
foods.push('Bloody Mary');
foods.push('Bloody Bull Shot');
foods.push('Screwdriver');
foods.push('Cosmopolitan');
foods.push('White Russian');
foods.push('Moscow Mule');
foods.push('Joy Tea');
foods.push('Infused Vodkas');
foods.push('Manhattan');
foods.push('Old-Fashioned');
foods.push('Whiskey Sour');
foods.push('Highball Or Rickey');
foods.push('Sazerac');
foods.push('Blood And Sand');
foods.push('Penicillin');
foods.push('Boulevardier');
foods.push('Mint Julep');
foods.push('Milk Punch');
foods.push('Hot Toddy');
foods.push('Cuba Libre');
foods.push('Daiquiri');
foods.push('Frozen Daiquiri');
foods.push('Jungle Bird');
foods.push('Caipirinha');
foods.push('Piña Colada');
foods.push('Mai Tai');
foods.push('Dark ’N Stormy');
foods.push('Mojito');
foods.push('Spanish Coffee');
foods.push('Grog');
foods.push('Hot Buttered Rum');
foods.push('Margarita');
foods.push('Frozen Margarita');
foods.push('Paloma');
foods.push('Tequila Sunrise');
foods.push('Brandy Alexander');
foods.push('Vieux Carré');
foods.push('Pisco Sour');
foods.push('Sidecar');
foods.push('Stinger');
foods.push('Nikolashka');
foods.push('Grasshopper');
foods.push('Shirley Temple');
foods.push('Cranberry Collins');
foods.push('Rock Shandy');
foods.push('Decorative Ice Mold');
foods.push('Champagne Punch');
foods.push('Sangría');
foods.push('Fish House Punch');
foods.push('Planter’S Punch');
foods.push('Chatham Artillery Punch');
foods.push('Bowle');
foods.push('Maitrank (May Wine)');
foods.push('Becker Deluxe Eggnog');
foods.push('Cooked Eggnog');
foods.push('Vegan Eggnog');
foods.push('Syllabub');
foods.push('Tom And Jerry');
foods.push('Glögg');
foods.push('Mulled Wine');
foods.push('Wassail');
foods.push('Mulled Cider');
foods.push('Kir');
foods.push('Mimosa');
foods.push('Black Velvet');
foods.push('Champagne Cocktail');
foods.push('French 75');
foods.push('White Wine Spritzer');
foods.push('Bellini');
foods.push('Aperol Spritz');
foods.push('Kalimotxo (Calimocho)');
foods.push('Michelada');
foods.push('Shandy');
foods.push('Roasted Nuts');
foods.push('Curried Nuts');
foods.push('Rosemary And Brown Sugar Nuts');
foods.push('Crisp Spicy Pecans');
foods.push('Thai-Spiced Peanuts');
foods.push('Boiled Peanuts');
foods.push('Roasted Chestnuts');
foods.push('Toasted Pumpkin Or Squash Seeds');
foods.push('Roasted Chickpeas');
foods.push('Edamame');
foods.push('Popcorn');
foods.push('Savory Additions To Popcorn');
foods.push('Kale Chips');
foods.push('Party Mix');
foods.push('Spanish-Style Marinated Olives');
foods.push('Potato Or Root Vegetable Chips');
foods.push('Tortilla Chips');
foods.push('Bagel Or Pita Chips');
foods.push('Crostini');
foods.push('Soda Crackers');
foods.push('Olive Oil Flatbread Crackers');
foods.push('Brown Butter–Hazelnut Crackers');
foods.push('Rye Crackers');
foods.push('Becker Sour Cream Dip');
foods.push('Red Onion Dip');
foods.push('Guacamole');
foods.push('Spinach Dip');
foods.push('Beer Cheese Dip');
foods.push('Queso Fundido (Hot Chorizo And Cheese Dip)');
foods.push('Hot Crab Dip');
foods.push('Baked Artichoke Dip');
foods.push('Seven-Layer Dip');
foods.push('Texas Caviar');
foods.push('Hummus');
foods.push('White Bean Dip With Rosemary And Garlic');
foods.push('Tangy Black Bean Dip');
foods.push('Any Bean Dip');
foods.push('Baba Ghanoush (Roasted Eggplant Dip)');
foods.push('Muhammara (Roasted Red Pepper And Walnut Dip)');
foods.push('Caponata (Eggplant Relish)');
foods.push('Tapenade (Olive-Caper Spread)');
foods.push('Anchoïade (Anchovy Dip)');
foods.push('Brandade De Morue (Creamy Salt Cod Dip)');
foods.push('Smoked Salmon Or Trout Spread');
foods.push('Cream Cheese Ball');
foods.push('Additions To Cheese Balls');
foods.push('Cheddar Cheese Ball');
foods.push('Treva’S Pimiento Cheese');
foods.push('Fromage Fort (Strong Cheese)');
foods.push('Blue Cheese Spread With Walnuts');
foods.push('Roasted Garlic And Parmesan Spread');
foods.push('Marinated Cheese');
foods.push('Fried Mozzarella Sticks');
foods.push('Fried Halloumi With Honey And Walnuts');
foods.push('Brie Baked In Pastry');
foods.push('Cheese Fondue');
foods.push('Nachos');
foods.push('Quesadillas');
foods.push('Bacon-Wrapped Dates');
foods.push('Melon And Prosciutto');
foods.push('Watermelon And Goat Cheese');
foods.push('Bagna Cauda');
foods.push('Marinated Vegetables');
foods.push('Broiled Stuffed Mushrooms Cockaigne');
foods.push('Stuffed Raw Vegetables');
foods.push('Potatoes Stuffed With Sour Cream And Caviar');
foods.push('Crispy Potato Skins');
foods.push('Patatas Or Papas Bravas (Spanish Fried Potatoes)');
foods.push('Jalapeño Poppers');
foods.push('Buffalo Chicken Wings');
foods.push('Thai-Style Chicken Wings');
foods.push('Lemon Rosemary Chicken Skewers');
foods.push('Five-Spice Ribs');
foods.push('Satay Skewers');
foods.push('Deviled Ham');
foods.push('Chicken Liver Pâté');
foods.push('Cocktail Meatballs');
foods.push('Keftedes (Greek Meatballs)');
foods.push('Pork And Mushroom Lettuce Wraps');
foods.push('Dolmas (Stuffed Grape Leaves)');
foods.push('Pot Stickers Or Gyoza');
foods.push('Steak Tartare');
foods.push('Rumaki');
foods.push('Negimaki (Beef And Scallion Rolls)');
foods.push('Grilled Or Broiled Shrimp Cockaigne');
foods.push('Cajun Popcorn Shrimp');
foods.push('Pickled Shrimp');
foods.push('Angels On Horseback');
foods.push('Oysters Rockefeller');
foods.push('Clams Casino');
foods.push('Canapés');
foods.push('Tea Sandwiches');
foods.push('Benedictine Sandwiches');
foods.push('Bruschetta');
foods.push('Cheese Puff Canapés');
foods.push('Ham Biscuits');
foods.push('Spinach Or Mushroom Phyllo Triangles');
foods.push('Quick Phyllo Samosas With Potatoes And Peas');
foods.push('Miniature Turnovers Or Tartlets');
foods.push('Miniature Quiches');
foods.push('Stuffed Choux Puffs');
foods.push('Gougères (Cheese Puffs)');
foods.push('Pigs In A Blanket');
foods.push('Puff Pastry Cheese Straws');
foods.push('Quick Cheese Crackers');
foods.push('Summer Rolls');
foods.push('Egg Rolls');
foods.push('Fried Wontons');
foods.push('Brown Beef Stock');
foods.push('White Veal Stock');
foods.push('Pork Or Ham Stock');
foods.push('Poultry Stock');
foods.push('Brown Poultry Stock');
foods.push('Demi-Glace And Meat Glaze');
foods.push('Household Stock');
foods.push('Game Stock');
foods.push('Bone Broth');
foods.push('Fish Stock Or Fumet');
foods.push('Shrimp Or Shellfish Stock');
foods.push('Dashi');
foods.push('Vegetable Stock');
foods.push('Brown Vegetable Stock');
foods.push('Mushroom Stock');
foods.push('Quick Chicken Or Beef Stock');
foods.push('Quick Seafood Stock');
foods.push('Court Bouillon');
foods.push('Vegetable Bouillon Paste');
foods.push('Chicken Broth');
foods.push('Beef Broth');
foods.push('Vegetable Broth');
foods.push('Parmesan Broth');
foods.push('Consommé');
foods.push('Egg Drop Soup');
foods.push('Stracciatella');
foods.push('Avgolemono (Greek Lemon Soup)');
foods.push('Miso Soup');
foods.push('Hearty Dumpling Soup');
foods.push('Matzo Ball Soup');
foods.push('Hot-And-Sour Soup');
foods.push('Vegetable Soup');
foods.push('Minestrone');
foods.push('Soupe Au Pistou (Provençal Vegetable Soup)');
foods.push('Winter Melon Soup');
foods.push('Green Pea Soup');
foods.push('Sauerkraut Soup');
foods.push('Kimchi Jjigae (Kimchi-Tofu Stew)');
foods.push('Garbure (Bean Soup With Vegetables)');
foods.push('Spicy Chickpea Soup');
foods.push('One-Eyed Bouillabaisse');
foods.push('Hungarian Mushroom Soup');
foods.push('Corn Chowder');
foods.push('Us Senate Bean Soup');
foods.push('Mediterranean White Bean Soup');
foods.push('Black Bean Soup');
foods.push('Megan’S Vegan Chili');
foods.push('Lentil Soup');
foods.push('Lentil Soup With Sausage And Potato');
foods.push('Split Pea Soup');
foods.push('Peanut Soup');
foods.push('Sopa De Ajo (Garlic And Bread Soup)');
foods.push('Pappa Al Pomodoro (Tuscan Bread And Tomato Soup)');
foods.push('Ribollita');
foods.push('French Onion Soup');
foods.push('Tortilla Soup');
foods.push('Becker Chicken Soup');
foods.push('Chicken Noodle Soup');
foods.push('Treva’S Chicken And Dumplings');
foods.push('Asopao De Pollo (Puerto Rican Chicken And Rice Soup)');
foods.push('Tom Kha Gai (Thai Chicken And Galangal Soup)');
foods.push('Cock-A-Leekie');
foods.push('Sopa De Lima (Yucatecan Chicken-Lime Soup)');
foods.push('Chicken Gumbo');
foods.push('Mulligatawny Soup');
foods.push('Beef Barley Soup');
foods.push('Pot-Au-Feu (French Simmered Beef And Vegetables)');
foods.push('Pho Bo (Vietnamese Beef Noodle Soup)');
foods.push('Spicy Sichuan Hot Pot');
foods.push('Borscht With Meat');
foods.push('Scotch Broth');
foods.push('Caldo Verde (Portuguese Greens Soup)');
foods.push('Italian Wedding Soup');
foods.push('Pepper Pot');
foods.push('Charleston She-Crab Soup');
foods.push('Lobster Bisque');
foods.push('Billi-Bi (Cream Of Mussel Soup)');
foods.push('Oyster Stew');
foods.push('Oyster Bisque');
foods.push('Tom Yum Goong (Thai Hot-And-Sour Shrimp Soup)');
foods.push('Seafood Gumbo');
foods.push('Caribbean Callaloo');
foods.push('Louisiana Court Bouillon');
foods.push('Cioppino');
foods.push('Bouillabaisse');
foods.push('New England Clam Chowder');
foods.push('Rhode Island Clam Chowder');
foods.push('Manhattan Clam Chowder');
foods.push('Salmon Chowder');
foods.push('Fish Chowder');
foods.push('Potato Leek Soup');
foods.push('Vichyssoise');
foods.push('Pumpkin Or Butternut Squash Soup');
foods.push('Tomato Soup');
foods.push('Roasted Cauliflower Soup');
foods.push('Cream Of Cauliflower Or Broccoli Soup');
foods.push('Broccoli-Cheddar Soup');
foods.push('Cream Of Mushroom Soup');
foods.push('Mushroom-Scallion Soup');
foods.push('Carrot-Ginger Soup');
foods.push('Cream Of Spinach Soup');
foods.push('Cream Of Watercress Soup');
foods.push('Beer-Cheese Soup');
foods.push('Cold Avocado Soup');
foods.push('Gazpacho');
foods.push('Becker Gazpacho');
foods.push('Cold Cucumber And Yogurt Soup');
foods.push('Dried Fruit Soup');
foods.push('Cherry Soup');
foods.push('Rose Hip Soup');
foods.push('Quick Borscht');
foods.push('Quick Cream Of Broccoli Or Cauliflower Soup');
foods.push('Chilled Fresh Tomato Cream Soup');
foods.push('Frico (Cheese Crisps)');
foods.push('Pan-Fried Goat Cheese Medallions');
foods.push('Becker House Salad');
foods.push('Wedge Salad');
foods.push('Bitter Greens With Apples And Pecans');
foods.push('Caesar Salad');
foods.push('Greek Salad');
foods.push('Megan’S Kale Salad');
foods.push('Sesame Greens With Roasted Shiitakes');
foods.push('Endive And Walnut Salad');
foods.push('Wilted Spinach Salad');
foods.push('Bistro Salad');
foods.push('Classic Coleslaw');
foods.push('Becker Coleslaw');
foods.push('Spicy Chinese-Style Slaw');
foods.push('Hot Slaw');
foods.push('Brussels Sprout Slaw With Spiced Yogurt');
foods.push('Chef’S Salad');
foods.push('Cobb Salad');
foods.push('Salade Niçoise');
foods.push('Lobster Salad Vinaigrette');
foods.push('Crab Louis');
foods.push('Seared Scallop, Grapefruit, And Radicchio Salad');
foods.push('The Mallory’S Shrimp Salad');
foods.push('Larb (Thai Minced Pork Salad)');
foods.push('Thai Beef Salad');
foods.push('Chinese Chicken Salad');
foods.push('Taco Salad');
foods.push('Chicken Or Turkey Salad');
foods.push('Chicken Salad Combinations');
foods.push('Ham Salad');
foods.push('Egg Salad');
foods.push('Vegan “Egg” Salad');
foods.push('Tuna Salad');
foods.push('Becker Tuna Salad');
foods.push('Lobster Or Shrimp Salad');
foods.push('Asparagus-Sesame Salad');
foods.push('Avocado And Citrus Salad');
foods.push('Avocado And Mango Salad');
foods.push('Beet, Fennel, And Citrus Salad With Horseradish');
foods.push('Carrot And Raisin Salad');
foods.push('Carottes Râpées (French Grated Carrot Salad)');
foods.push('Shaved Carrot Salad');
foods.push('Celery Root Rémoulade');
foods.push('Dee’S Corn And Tomato Salad');
foods.push('Cucumber Salad');
foods.push('Chinese Smacked Cucumber Salad');
foods.push('Arugula And Heart Of Palm Salad');
foods.push('Jicama Salad');
foods.push('Three-Pea Salad');
foods.push('Potato Salad');
foods.push('Creamy Potato Salad');
foods.push('German Potato Salad');
foods.push('Tomato Salad');
foods.push('Shirazi Or Israeli Salad');
foods.push('Panzanella (Tuscan Bread And Tomato Salad)');
foods.push('Fattoush (Lebanese Pita Salad)');
foods.push('Waldorf Salad');
foods.push('Spicy Watermelon Salad');
foods.push('Green Papaya Salad');
foods.push('Sicilian Orange, Fennel, And Onion Salad');
foods.push('Basic Bean Salad');
foods.push('Shaved Fennel And White Bean Salad');
foods.push('Edamame And Carrot Salad');
foods.push('Chickpea And Roasted Cauliflower Salad');
foods.push('Rachel’S Kale And Lentil Salad');
foods.push('Rice Salad With Chicken And Olives');
foods.push('Wild Rice Salad With Sausage');
foods.push('Brown Rice Salad With Dates And Oranges');
foods.push('Tabbouleh');
foods.push('Warm Barley, Mushroom, And Asparagus Salad');
foods.push('Wheat Salad With Pesto And Zucchini');
foods.push('Quinoa Salad With Broccoli And Feta');
foods.push('Basic Pasta Salad');
foods.push('Pasta Salad With Chicken Or Shrimp');
foods.push('Creamy Macaroni Salad For A Crowd');
foods.push('Basic Savory Aspic');
foods.push('Tomato Aspic');
foods.push('Basic Cream Cheese Spread (Schmear)');
foods.push('Blt');
foods.push('Club Sandwich');
foods.push('Megan’S Avocado Club Sandwich');
foods.push('Muffuletta');
foods.push('Pan Bagnat (Provençal Pressed Tuna Sandwich)');
foods.push('Bagels And Lox');
foods.push('Sub Or Hero Sandwich');
foods.push('Lobster Roll');
foods.push('Banh Mi (Vietnamese Sandwiches)');
foods.push('Hot Roast Beef Sandwich');
foods.push('Fried Soft-Shell Crab Sandwich');
foods.push('Sloppy Joe');
foods.push('Sausage And Pepper Sub');
foods.push('Philly Cheese Steak');
foods.push('Oyster Po’Boy');
foods.push('Grilled Cheese Sandwich');
foods.push('Reuben Sandwich');
foods.push('Croque-Monsieur');
foods.push('Croque-Madame');
foods.push('Monte Cristo');
foods.push('Cuban Sandwich');
foods.push('Panini');
foods.push('Tortas');
foods.push('Tuna Melt');
foods.push('Hot Brown');
foods.push('Hot Dogs');
foods.push('Corn Dogs');
foods.push('Hamburgers');
foods.push('Patty Melt');
foods.push('Beet Burgers');
foods.push('Roasted Mushroom Burgers');
foods.push('Flatbread Or Pita Sandwich');
foods.push('Sabich (Israeli Pita Sandwich)');
foods.push('Tacos');
foods.push('Tostadas');
foods.push('Burritos');
foods.push('Mission-Style Burritos');
foods.push('Breakfast Burritos');
foods.push('Soft-Boiled Eggs');
foods.push('Hard-Boiled Eggs');
foods.push('Deviled Eggs');
foods.push('Additions To Deviled Eggs');
foods.push('Pickled Eggs');
foods.push('Beet-Pickled Eggs');
foods.push('Curry-Pickled Eggs');
foods.push('Son-In-Law Eggs');
foods.push('Scotch Eggs');
foods.push('Poached Eggs');
foods.push('Coddled Eggs');
foods.push('Slow-Poached Eggs');
foods.push('Eggs Florentine');
foods.push('Eggs Benedict');
foods.push('Latkes Benedict');
foods.push('Oeufs En Meurette (Poached Eggs In Red Wine Sauce)');
foods.push('Shakshouka (Eggs Poached In Tomato-Pepper Sauce)');
foods.push('Eggs In Purgatory');
foods.push('Baked Eggs');
foods.push('Additions To Baked Eggs');
foods.push('Lost Eggs');
foods.push('Fried Eggs');
foods.push('Frico Eggs');
foods.push('Bread Crumb–Fried Eggs');
foods.push('Additions To Fried Eggs');
foods.push('Egg In A Basket');
foods.push('Huevos Rancheros');
foods.push('Breakfast Chilaquiles');
foods.push('Scrambled Eggs');
foods.push('Additions To Scrambled Eggs');
foods.push('Tex-Mex Migas');
foods.push('Matzo Brei');
foods.push('Egg Foo Young');
foods.push('French Omelet (Rolled Or Folded)');
foods.push('Fillings For Omelets');
foods.push('Firm Diner-Style Omelet');
foods.push('Frittata');
foods.push('Kuku Sabzi (Persian Herbed Omelet)');
foods.push('Hangtown Fry');
foods.push('Artichoke Frittata For A Crowd');
foods.push('Tortilla Española (Spanish Potato Omelet)');
foods.push('Souffléed Omelet');
foods.push('Cheese Soufflé Cockaigne');
foods.push('Vegetable Soufflé');
foods.push('Goat Cheese And Walnut Soufflés');
foods.push('Vegetable Timbales');
foods.push('Quiche Lorraine');
foods.push('Cheese Quiche');
foods.push('Additions To Quiche');
foods.push('Tomato And Goat Cheese Quiche');
foods.push('Leek Tart');
foods.push('Basic Strata');
foods.push('Strata Combinations');
foods.push('Sausage And Mushroom Strata');
foods.push('Asparagus Strata');
foods.push('Crab Strata');
foods.push('Fruit Salad');
foods.push('Ambrosia');
foods.push('Macerated Fruit');
foods.push('Citrus Salad');
foods.push('Summer Fruit Salad');
foods.push('Dried Fruit Compote');
foods.push('Charoset');
foods.push('Panforte Di Siena (Dried Fruit Cake)');
foods.push('No-Bake Fruit And Nut Bars');
foods.push('Poaching Liquids For Fruits');
foods.push('Poached Fruit');
foods.push('Roasted Fruit');
foods.push('Grilled Or Broiled Fruit');
foods.push('Grilled Or Broiled Fruit Kebabs With Honey And Lime');
foods.push('Fruit Brûlé');
foods.push('Sautéed Fruit');
foods.push('Cooked Fruit Puree');
foods.push('Garnishes For Pureed Fruits');
foods.push('Fruit Fool');
foods.push('Sautéed Apple Rings');
foods.push('Applesauce');
foods.push('Baked Apples');
foods.push('Baked Apples Stuffed With Sausage');
foods.push('Baked Honeyed Apricots');
foods.push('Chocolate-Dipped Bananas');
foods.push('Baked Bananas');
foods.push('Bananas Foster');
foods.push('Campfire Bananas');
foods.push('Strawberries Cockaigne');
foods.push('Chocolate-Dipped Strawberries');
foods.push('Strawberries Romanoff');
foods.push('Blueberry Compote');
foods.push('Blackberry Or Raspberry Flummery');
foods.push('Cranberry Sauce');
foods.push('Whole-Berry Cranberry Sauce');
foods.push('Additions To Cranberry Sauce');
foods.push('Uncooked Cranberry Relish');
foods.push('Sour Cherries With Ricotta, Honey, And Almonds');
foods.push('Cherries Jubilee');
foods.push('Macerated Cherries With Herbs');
foods.push('Oranges In Syrup');
foods.push('Kumquat Compote');
foods.push('Broiled Grapefruit');
foods.push('Coconut-Cucumber Salad');
foods.push('Sautéed Dates With Almonds');
foods.push('Savory Stuffed Dates');
foods.push('Baked Figs With Ricotta');
foods.push('Fig Compote With Lemon And Ginger');
foods.push('Melon Baskets Or Fruit Cups');
foods.push('Grilled Peaches With Goat Cheese');
foods.push('Baked Stuffed Peaches');
foods.push('Caramelized Grilled Pineapple');
foods.push('Pineapple Tidbits');
foods.push('Stewed Prunes');
foods.push('Grenadine');
foods.push('Pomegranate Molasses');
foods.push('Melon With Prickly Pear Sauce');
foods.push('Baked Quinces');
foods.push('Membrillo (Quince Paste)');
foods.push('Roasted Rhubarb');
foods.push('Poached Rhubarb');
foods.push('Basic Vegetable Stir-Fry');
foods.push('Vegetable Breakfast Hash');
foods.push('Glazed Root Vegetables');
foods.push('Root Vegetable Puree');
foods.push('Root Vegetable Braise');
foods.push('Battered And Deep-Fried Vegetables');
foods.push('Vegetables À La Grecque');
foods.push('Ratatouille Provençale');
foods.push('Vegetable Tian');
foods.push('Vegetable Tagine');
foods.push('Steamed Artichokes');
foods.push('Garlic-Braised Artichokes');
foods.push('Stuffed Artichokes Alla Romana');
foods.push('Fried Artichokes');
foods.push('Braised Baby Artichokes And Peas');
foods.push('Steamed Asparagus');
foods.push('Roasted Asparagus');
foods.push('Stir-Fried Asparagus');
foods.push('Asparagus With Orange And Hazelnuts');
foods.push('Steamed Or Boiled Green Beans');
foods.push('Roasted Green Beans');
foods.push('Green Bean Casserole');
foods.push('Braised Green Beans');
foods.push('Sichuan-Style Dry-Fried Beans');
foods.push('Braised Lima Beans');
foods.push('Wanda’S Stewed Cranberry Beans');
foods.push('Baghali Ghatogh (Iranian Fava Bean Stew With Eggs)');
foods.push('Roman-Style Fava Beans');
foods.push('Frijoles De La Olla');
foods.push('Tuscan Beans');
foods.push('Ful Medames (Simmered Fava Beans)');
foods.push('Falafel');
foods.push('Feijoada (Brazilian Black Bean Stew)');
foods.push('Refried Beans');
foods.push('Jamaican Stew Peas');
foods.push('Baked Beans');
foods.push('Cassoulet');
foods.push('Red Beans And Rice');
foods.push('Black-Eyed Peas And Greens');
foods.push('Chana Masala (Tomato-Chickpea Curry)');
foods.push('Simmered Lentils');
foods.push('Dal (Indian Lentil Stew)');
foods.push('Braised Lentils With Sausage');
foods.push('Steamed Or Simmered Beets');
foods.push('Baked Or Roasted Beets');
foods.push('Megan’S Beets With Goat Cheese');
foods.push('Beets With Their Greens');
foods.push('Steamed Broccoli');
foods.push('Roasted Broccoli');
foods.push('Broccoli Cakes');
foods.push('Broccoli-Cheese Casserole');
foods.push('Garlic-Braised Broccoli Rabe');
foods.push('Roasted Brussels Sprouts');
foods.push('Braised Brussels Sprouts With Chestnuts');
foods.push('Becker Brussels Sprouts');
foods.push('Brussels Sprout Gratin');
foods.push('Kinpira Gobo (Japanese Braised Burdock And Carrots)');
foods.push('Sautéed Cabbage');
foods.push('Cabbage With Potatoes And Ham');
foods.push('Stir-Fried Bok Choy With Mushrooms');
foods.push('Roasted Cabbage Wedges With Yogurt Sauce');
foods.push('Cabbage Gratin');
foods.push('Braised Red Cabbage');
foods.push('Braised Sauerkraut');
foods.push('Sauerkraut Fritters');
foods.push('Okonomiyaki (Japanese Cabbage Pancakes)');
foods.push('Stuffed Cabbage Rolls');
foods.push('Roasted Cactus Pad Salad');
foods.push('Simmered Cardoons');
foods.push('Glazed Carrots');
foods.push('Roasted Carrots');
foods.push('Charred Carrots');
foods.push('Roasted Cauliflower Wedges');
foods.push('Roasted Cauliflower With Green Olives And Lemon');
foods.push('Tandoori Cauliflower');
foods.push('Cauliflower With Brown Butter Bread Crumbs');
foods.push('Creamy Mashed Cauliflower');
foods.push('Scalloped Cauliflower');
foods.push('Aloo Gobi (Curried Cauliflower And Potatoes)');
foods.push('Gobi Manchurian (Indian-Chinese Fried Cauliflower)');
foods.push('Stir-Fried Celery');
foods.push('Baked Celery Root');
foods.push('Boiled Chestnuts');
foods.push('Chestnut Compote');
foods.push('Belgian Endive Au Gratin');
foods.push('Grilled Treviso With Sauce Gribiche');
foods.push('Utica Greens (Spicy Baked Escarole)');
foods.push('Braised Radicchio');
foods.push('Corn On The Cob');
foods.push('Grilled, Roasted, Or Broiled Corn');
foods.push('Elotes (Mexican Grilled Corn)');
foods.push('Sautéed Corn');
foods.push('Creamed Corn');
foods.push('Corn Pudding');
foods.push('Additions To Corn Pudding');
foods.push('Cheese-Chile Corn Squares');
foods.push('Succotash');
foods.push('Fresh Corn Fritters');
foods.push('Roasted Eggplant');
foods.push('Miso-Glazed Eggplant');
foods.push('Fried Eggplant');
foods.push('Eggplant Parmigiana');
foods.push('Rolled Stuffed Eggplant');
foods.push('Moussaka');
foods.push('Braised Fennel');
foods.push('Grilled Fennel And Tomatoes With Olives And Basil');
foods.push('Roasted Garlic');
foods.push('Garlic Confit');
foods.push('Garlic Chips');
foods.push('Southern-Style Greens');
foods.push('Wilted Tender Greens');
foods.push('Creamed Spinach');
foods.push('Spinach With Pine Nuts And Raisins');
foods.push('Braised Greens With Garlic');
foods.push('Gumbo Z’Herbes');
foods.push('Spinach Pakoras');
foods.push('Sautéed Shredded Collard Greens');
foods.push('Palak Paneer (Curried Spinach With Fresh Cheese)');
foods.push('Braised Leeks');
foods.push('Melted Leeks');
foods.push('Leeks Vinaigrette');
foods.push('Leek Gratin');
foods.push('Grilled Leeks With Romesco Sauce');
foods.push('Glamorgan Sausages (Vegetarian Leek And Cheese “Sausages”)');
foods.push('Sautéed Mushrooms');
foods.push('Creamed Mushrooms');
foods.push('Champignones Al Ajillo (Garlicky Spanish-Style Mushrooms)');
foods.push('Mushroom Ragout');
foods.push('Roasted Mushrooms');
foods.push('Mushroom Bacon');
foods.push('Grilled Mushrooms');
foods.push('Duxelles');
foods.push('Mushroom Confit');
foods.push('Okra And Tomato Stew');
foods.push('Fried Okra');
foods.push('Bhindi Kurkuri (Crispy Indian-Style Fried Okra)');
foods.push('Sautéed Onions');
foods.push('Caramelized Onions');
foods.push('Creamed Pearl Onions');
foods.push('Onion Rings');
foods.push('Crispy Fried Shallots');
foods.push('Grilled Sweet Onions');
foods.push('Oven- Or Fire-Baked Whole Onions');
foods.push('Roasted Shallots');
foods.push('Baked Onions Stuffed With Spinach And Sausage');
foods.push('Korean Green Onion Pancake');
foods.push('Parsnip-Cheese Gratin');
foods.push('Braised Garden Peas');
foods.push('Stir-Fried Snow Peas');
foods.push('Peas With Prosciutto And Onions');
foods.push('Pea And Ricotta Toasts');
foods.push('Roasted Peppers');
foods.push('Stuffed Bell Peppers');
foods.push('Rajas Con Crema (Creamy Roasted Poblano Strips)');
foods.push('Charred Shishito Or Padrón Peppers');
foods.push('Chiles Rellenos');
foods.push('Roasted Plantains');
foods.push('Fried Plantains');
foods.push('Boiled Potatoes');
foods.push('Mashed Potatoes');
foods.push('Additions To Mashed Potatoes');
foods.push('Colcannon (Mashed Potatoes With Kale Or Cabbage And Green Onions)');
foods.push('Mashed Potato Casserole For A Crowd');
foods.push('Pan-Fried Mashed Potato Cakes');
foods.push('Potatoes Au Gratin (Scalloped Potatoes)');
foods.push('Baked Potatoes');
foods.push('Twice-Baked Potatoes');
foods.push('Duchess Potatoes');
foods.push('Roasted Potatoes');
foods.push('Hasselback Potatoes');
foods.push('Crispy Smashed Potatoes');
foods.push('Pommes Anna');
foods.push('Potato Kugel');
foods.push('Pan-Fried Potatoes');
foods.push('Hash Brown Potatoes');
foods.push('Latkes (Potato Pancakes)');
foods.push('Potatoes Rösti');
foods.push('Souffléed Or Puffed Potatoes');
foods.push('French Fries');
foods.push('Additions To French Fries');
foods.push('Jojos (Fried Potato Wedges)');
foods.push('Oven “French-Fried” Potatoes');
foods.push('Radishes With Green Onion');
foods.push('Peas And Radishes With Miso Butter');
foods.push('Salsify With Herbs');
foods.push('Sautéed Summer Squash');
foods.push('Summer Squash Casserole');
foods.push('Baked Stuffed Zucchini');
foods.push('Louisiana-Style Chayote');
foods.push('Zucchini Fans');
foods.push('Baked Or Roasted Winter Squash');
foods.push('Mashed Winter Squash');
foods.push('Baked Butternut Squash Stuffed With Sausage And Apples');
foods.push('Pumpkin Curry');
foods.push('Squash Blossoms Stuffed With Cheese And Herbs');
foods.push('Sunchokes In Garlic Butter');
foods.push('Crispy Roasted Sunchokes');
foods.push('Mashed Sweet Potatoes');
foods.push('Sweet Potato Pudding');
foods.push('Twice-Baked Sweet Potatoes');
foods.push('Candied Sweet Potatoes');
foods.push('Sweet Potato Fries');
foods.push('Sweet Potato Stew With Peanuts');
foods.push('Poi');
foods.push('Stewed Tomatoes Or Tomatoes Creole');
foods.push('Fried Green Tomatoes');
foods.push('Tomatoes Provençale');
foods.push('Broiled Tomatoes');
foods.push('Slow-Roasted Tomatoes');
foods.push('Scalloped Tomatoes');
foods.push('Hot Stuffed Tomatoes');
foods.push('Braised Turnips With Leeks And Bacon');
foods.push('Yuca With Citrus And Garlic');
foods.push('Mapo Dofu (Sichuan-Style Tofu)');
foods.push('Tofu Scramble');
foods.push('Agedashi Tofu');
foods.push('Crispy Pan-Fried Tofu');
foods.push('Baked Marinated Tofu');
foods.push('Sambal Goreng Tempeh');
foods.push('Seasoned Tempeh Crumbles');
foods.push('Caramelized Tamarind Tempeh');
foods.push('Meatless Dinner Loaf');
foods.push('Seitan');
foods.push('Kung Pao Seitan');
foods.push('Pecan And Cheddar “Sausage” Patties');
foods.push('Frittata Di Scammaro');
foods.push('Leftover Pasta Casserole');
foods.push('Fresh Pasta Dough');
foods.push('Semolina Pasta');
foods.push('Whole Wheat Pasta');
foods.push('Spinach Pasta');
foods.push('Herb Pasta');
foods.push('Fresh Egg Noodle Dough');
foods.push('Boiled Pasta Or Egg Noodles');
foods.push('Fettuccine With Butter And Cheese');
foods.push('Fettuccine With Prosciutto And Peas');
foods.push('Spaghetti Carbonara');
foods.push('Spaghetti Aglio E Olio (Spaghetti With Garlic And Oil)');
foods.push('Macaroni And Cheese');
foods.push('Baked Macaroni And Cheese');
foods.push('Kimchi Mac');
foods.push('Macaroni And Cheese For A Crowd');
foods.push('Fettuccine With Fresh Herbs');
foods.push('Pasta Primavera');
foods.push('Pasta Alla Norma (Pasta With Eggplant And Tomato Sauce)');
foods.push('Pasta Con Le Sarde (Pasta With Sardines And Fennel)');
foods.push('One-Pan Pasta With Tomatoes And Herbs');
foods.push('Fettuccine With Salmon And Asparagus');
foods.push('Linguine With Clam Sauce');
foods.push('Penne With Vodka Sauce');
foods.push('Tagliatelle With Wilted Greens');
foods.push('Pasta E Fagioli (Pasta And Beans)');
foods.push('Orecchiette With Sausage And Broccoli Rabe');
foods.push('Rossejat De Fideos (Spanish Toasted Noodles)');
foods.push('Buttered Egg Noodles');
foods.push('Additions To Egg Noodles');
foods.push('Haluski (Fried Cabbage And Noodles)');
foods.push('Lo Mein');
foods.push('Chow Mein');
foods.push('Beef Chow Fun');
foods.push('Sesame Noodles');
foods.push('Dan Dan Noodles (Spicy Sichuan Noodles)');
foods.push('Khao Soi Gai (Thai Chicken Curry Noodles)');
foods.push('Pad Thai');
foods.push('Kuaytiaw Khua Kai (Thai Fried Rice Noodles With Chicken And Romaine)');
foods.push('Udon Noodles In Broth');
foods.push('Shoyu Ramen');
foods.push('Miso Ramen');
foods.push('Cold Soba Noodles');
foods.push('Japchae (Korean Sweet Potato Noodles)');
foods.push('Bún (Vietnamese Rice Noodle Bowls)');
foods.push('Dumplings');
foods.push('Farina Dumplings Cockaigne');
foods.push('Cornmeal Dumplings');
foods.push('Butterklösse (Butter Dumplings)');
foods.push('Kartoffelklösse (Potato Dumplings)');
foods.push('Potato Gnocchi');
foods.push('Malfatti (Spinach-Ricotta Gnocchi)');
foods.push('Roman-Style Baked Gnocchi');
foods.push('Baked Gnudi With Brown Butter And Sage');
foods.push('Gnocchi Parisienne');
foods.push('Spätzle');
foods.push('Pastitsio');
foods.push('Mushroom-Walnut Noodle Kugel');
foods.push('Sweet Noodle Kugel');
foods.push('Baked Manicotti Or Shells');
foods.push('Baked Cannelloni Or Crespelles');
foods.push('Lasagne');
foods.push('Lasagne Bolognese');
foods.push('Roasted Mushroom Lasagne');
foods.push('Roasted Vegetable Lasagne');
foods.push('Cheese Filling');
foods.push('Mushroom Filling');
foods.push('Meat And Spinach Filling');
foods.push('Three-Meat Filling');
foods.push('Winter Squash Filling');
foods.push('Ravioli');
foods.push('Tortellini');
foods.push('Potato And Cheese Filling');
foods.push('Sauerkraut-Mushroom Filling');
foods.push('Sweet Cheese Filling');
foods.push('Sour Cherry Filling');
foods.push('Vareniki Or Pierogi');
foods.push('Kreplach');
foods.push('Pelmeni');
foods.push('Wontons');
foods.push('Vegetable Wontons');
foods.push('Seafood Or Pork Shumai');
foods.push('Bāo (Chinese Steamed Buns)');
foods.push('Barley “Risotto” With Mushrooms');
foods.push('Kasha Varnishkes (Bow-Ties With Kasha)');
foods.push('Buckwheat Pilaf');
foods.push('Cornmeal Mush');
foods.push('Creamy Polenta');
foods.push('Becker Rustic Polenta');
foods.push('Cheesy Baked Polenta Or Grits');
foods.push('Souffléed Baked Polenta Or Grits');
foods.push('Fried Polenta');
foods.push('Creamy Grits');
foods.push('Green Posole');
foods.push('Red Posole');
foods.push('Chicken And Cheese Tamales');
foods.push('Banana Leaf Tamales');
foods.push('Three Sisters Tamales');
foods.push('Saffron Millet');
foods.push('Cheesy Millet Spoon Bread With Chiles');
foods.push('Millet Cakes With Parmesan And Sun-Dried Tomatoes');
foods.push('Megan’S Seeded Olive Oil Granola');
foods.push('Low-Sugar Granola');
foods.push('Muesli');
foods.push('Baked Oatmeal');
foods.push('Pumpkin Baked Oatmeal');
foods.push('Overnight Steel-Cut Oats');
foods.push('Jeweled Quinoa');
foods.push('Quinoa Pilaf');
foods.push('Baked Rice');
foods.push('Rice Pilaf');
foods.push('Mujadara (Lentils And Rice With Browned Onions)');
foods.push('Becker Rice And Noodle Pilaf');
foods.push('Spanish Rice');
foods.push('Hoppin’ John');
foods.push('Jamaican Rice And Peas');
foods.push('Chicken Jambalaya');
foods.push('Cajun Dirty Rice');
foods.push('Fried Rice');
foods.push('Additions To Fried Rice');
foods.push('Kimchi Fried Rice');
foods.push('Congee');
foods.push('Persian Rice');
foods.push('Coconut Rice');
foods.push('Indian Lemon Rice');
foods.push('Paella Valenciana');
foods.push('Shellfish Paella');
foods.push('Gohan (Plain Japanese Rice)');
foods.push('Shari (Sushi Rice)');
foods.push('Makizushi (Rolled Sushi)');
foods.push('Risotto');
foods.push('Risi E Bisi (Rice And Peas)');
foods.push('Risotto With Mushrooms');
foods.push('Fresh Corn Risotto');
foods.push('Pressure-Cooker Risotto');
foods.push('Rye Pilaf');
foods.push('Wheat Berries With Sautéed Onions And Dried Fruits');
foods.push('Wheat Berries And Brown Rice');
foods.push('Freekeh With Greens, Chickpeas, And Halloumi');
foods.push('Farrotto');
foods.push('Couscous With Pine Nuts And Raisins');
foods.push('Couscous With Chicken, Lemon, And Olives');
foods.push('Israeli Couscous Pilaf');
foods.push('Wild Rice With Sautéed Mushrooms');
foods.push('Raw Shellfish On The Half Shell');
foods.push('Mixed Shellfish In Tomato Sauce');
foods.push('Shellfish With Mushrooms And Greens');
foods.push('Deep-Fried Shellfish');
foods.push('Pan-Fried Shellfish');
foods.push('Broiled Oysters');
foods.push('Grilled Oysters');
foods.push('Baked Oysters On The Half Shell');
foods.push('Oysters Mosca');
foods.push('Scalloped Oysters');
foods.push('Creamed Oysters');
foods.push('Steamed Mussels');
foods.push('Buttered Baked Mussels');
foods.push('Steamed Clams');
foods.push('Baked Soft-Shell Clams');
foods.push('Baked Stuffed Clams (Stuffies)');
foods.push('Clambake');
foods.push('Stir-Fried Clams Or Mussels With Oyster Sauce');
foods.push('Thai Clam Pot');
foods.push('Scallop Ceviche');
foods.push('Scallops Meunière');
foods.push('Coquilles St. Jacques (Sea Scallop Gratin)');
foods.push('Seared Sea Scallops');
foods.push('Sautéed Abalone');
foods.push('Deep-Fried Soft-Shell Crabs');
foods.push('Grilled Or Broiled Soft-Shell Crabs');
foods.push('Steamed Blue Crabs');
foods.push('Poached Or Boiled Crabs');
foods.push('Crab Cakes');
foods.push('Singaporean Chilli Crab');
foods.push('Steamed Lobster');
foods.push('Boiled Lobster');
foods.push('Grilled Or Broiled Lobster');
foods.push('Lobster Américaine (Or Armoricaine)');
foods.push('Baked Stuffed Lobster');
foods.push('Lobster Thermidor');
foods.push('Lobster Newburg');
foods.push('Quick Skillet Shrimp');
foods.push('Blackened Shrimp');
foods.push('Salt-And-Pepper Shrimp Or Squid');
foods.push('Poached Or “Boiled” Shrimp');
foods.push('Becker Barbecued Shrimp');
foods.push('Shrimp And Grits');
foods.push('Camarones A La Diabla (Spicy Simmered Shrimp)');
foods.push('Shrimp Creole');
foods.push('Camarones Al Mojo De Ajo (Shrimp In Garlic-Citrus Sauce)');
foods.push('Coconut Shrimp');
foods.push('Shrimp Scampi');
foods.push('Grilled Or Broiled Shrimp Or Scallops');
foods.push('Shrimp Fajitas');
foods.push('Baked Stuffed Jumbo Shrimp');
foods.push('Thai Shrimp Curry');
foods.push('Shrimp Or Crawfish Étouffée');
foods.push('Boiled Crayfish');
foods.push('Cajun-Style Crawfish Boil');
foods.push('Grilled Or Charred Squid');
foods.push('Stuffed Squid');
foods.push('Grilled Marinated Octopus');
foods.push('Tako Poke (Korean-Style Octopus Poke)');
foods.push('Conch Or Whelk Salad');
foods.push('Turtle Soup');
foods.push('Baked Buttered Snails');
foods.push('Braised Frog Legs');
foods.push('Deep-Fried Frog Legs');
foods.push('Ceviche');
foods.push('Tuna Or Salmon Poke');
foods.push('Baked Or Slow-Roasted Fish');
foods.push('High-Heat Roasted Fish');
foods.push('Paupiettes (Stuffed Fish Fillets)');
foods.push('Fish En Papillote (Fish Baked In Parchment)');
foods.push('Additions To Fish Baked In Parchment');
foods.push('Oven-Fried Fish Fillets');
foods.push('Veracruz-Style Snapper');
foods.push('Fish Boulangère (Baked Fish With Potatoes And Pearl Onions)');
foods.push('Fish Baked In Salt');
foods.push('Poached Fish');
foods.push('Poaching Liquids For Fish');
foods.push('Poached Fish Quenelles');
foods.push('Gefilte Fish');
foods.push('Braised Fish Fillets With Lemon And Capers');
foods.push('Chinese Steamed Fish');
foods.push('Butter- Or Olive Oil-Poached Fish');
foods.push('Fish Curry');
foods.push('Microwaved Fish Fillets');
foods.push('Grilled Or Broiled Whole Fish');
foods.push('Grilled Or Broiled Whole Trout With Bacon');
foods.push('Grilled Whole Stuffed Trout');
foods.push('Spice-Rubbed Grilled Or Broiled Fish');
foods.push('Grilled Fish Steaks');
foods.push('Fish Kebabs With Vinaigrette');
foods.push('Teriyaki-Grilled Fish Steaks');
foods.push('Planked Fish');
foods.push('Grilled Or Broiled Fish Fillets');
foods.push('Grilled Or Broiled Fish Fillets With Herbs');
foods.push('Broiled Fish Fillets With Bread Crumbs');
foods.push('Black Cod Misozuke');
foods.push('Pan-Fried Fish Fillets Or Steaks');
foods.push('Breaded Pan-Fried Fish');
foods.push('Sautéed Smelts Or Anchovies');
foods.push('Brook Trout Meunière');
foods.push('Pan-Fried Skate With Black Butter');
foods.push('Sautéed Pepper-Crusted Fish Steaks');
foods.push('Blackened Fish Steaks Or Fillets');
foods.push('Pan-Fried Salmon Cakes');
foods.push('Pan-Fried Shad Roe');
foods.push('Fried Fish');
foods.push('Southern-Style Deep-Fried Catfish');
foods.push('Pla Raad Prik (Thai Fried Fish With Tamarind-Garlic Sauce)');
foods.push('Fish And Chips');
foods.push('Thai Fish Cakes');
foods.push('Escabeche (Spanish Marinated Fried Fish)');
foods.push('Fried Tiny Fish');
foods.push('Gravlax (Cured Salmon)');
foods.push('Hot-Smoked Salmon');
foods.push('Smoked Salmon Hash');
foods.push('Salt Herring And Potatoes');
foods.push('Kedgeree');
foods.push('Roast Chicken');
foods.push('Roast Chicken With Vegetables');
foods.push('Chicken Under A Brick');
foods.push('Roast Cornish Hens');
foods.push('Glazed Stuffed Cornish Hens');
foods.push('Roasted Chicken Parts');
foods.push('Chicken Breasts Baked On A Bed Of Mushrooms');
foods.push('Sicilian-Style Stuffed Chicken Breasts');
foods.push('Mediterranean Chicken Breast Packets');
foods.push('Additions To Broiled Or Grilled Chicken');
foods.push('Broiled Chicken');
foods.push('Grilled Chicken');
foods.push('Broiled Or Grilled Barbecued Chicken');
foods.push('Broiled Or Grilled Teriyaki Chicken');
foods.push('Smoked Chicken');
foods.push('Gai Yang (Thai-Style Grilled Cornish Hens)');
foods.push('Broiled Cornish Hens');
foods.push('Chicken Kebabs');
foods.push('Jamaican Jerk Chicken');
foods.push('Tandoori Chicken Or Chicken Tikka');
foods.push('Chicken Hobo Packs');
foods.push('Pan-Fried Or Sautéed Chicken');
foods.push('Pan-Fried Chicken Cutlets');
foods.push('Chicken Piccata');
foods.push('Chicken Marsala');
foods.push('Chicken Parmigiana');
foods.push('Chicken Fingers');
foods.push('Chicken Kiev');
foods.push('Chicken Cordon Bleu');
foods.push('Stir-Fried Garlic Chicken');
foods.push('Skillet Fried Chicken');
foods.push('Crispy Deep-Fried Chicken');
foods.push('Nashville Hot Chicken');
foods.push('Oven-Fried Chicken');
foods.push('Poached Chicken');
foods.push('Shoyu Chicken');
foods.push('Creamed Chicken');
foods.push('Chicken With 40 Cloves Of Garlic');
foods.push('Coq Au Vin (Chicken Braised In Wine)');
foods.push('French Casserole Chicken');
foods.push('Thai-Style Yellow Chicken Curry');
foods.push('Thai-Style Green Chicken Curry');
foods.push('Chicken Paprika');
foods.push('Chicken Fricassee');
foods.push('Chicken And Dumplings');
foods.push('Chicken Cacciatore');
foods.push('Chicken Marengo');
foods.push('Country Captain');
foods.push('Chicken Makhini Masala');
foods.push('Basque Chicken');
foods.push('Arroz Con Pollo (Chicken And Rice)');
foods.push('Chicken Tagine With Chickpeas');
foods.push('Chicken Chili Verde');
foods.push('Chicken Tinga');
foods.push('Chicken Étouffée');
foods.push('Classic Roast Turkey');
foods.push('High-Heat Roast Turkey');
foods.push('Roast Turkey Breast');
foods.push('Grilled Turkey');
foods.push('Deep-Fried Turkey');
foods.push('Turkey In Red Mole');
foods.push('Chicken And Apple Sausage');
foods.push('Turkey Or Chicken Burgers');
foods.push('Turkey Or Chicken Loaf');
foods.push('Turkey Or Chicken Meatballs');
foods.push('Roast Duck Or Goose');
foods.push('Glazed Roast Duck Or Goose');
foods.push('Chinese Roast Duck');
foods.push('Pan-Seared Duck Breasts');
foods.push('Grilled Duck Breasts With Hoisin-Ginger Sauce');
foods.push('Fesenjoon (Persian Duck And Pomegranate Stew)');
foods.push('Duck Or Goose Confit');
foods.push('Duck Or Goose Rillettes');
foods.push('Roast Guinea Fowl');
foods.push('Grilled Or Broiled Squab');
foods.push('Salmi Of Squab');
foods.push('Chinese-Style Smoked Squab');
foods.push('Emu Or Ostrich Fillets');
foods.push('Roast Wild Duck');
foods.push('Seared Wild Duck Or Goose Breasts');
foods.push('Wild Duck Fricassee');
foods.push('Glazed Grilled Duck Legs');
foods.push('Wild Turkey Roasted In A Baking Bag');
foods.push('Wild Turkey Or Goose Legs Braised In Red Wine');
foods.push('Roast Pheasant');
foods.push('Pheasant Braised With Gin And Juniper');
foods.push('Braised Pheasant With Apples');
foods.push('Roasted Grouse');
foods.push('Port-Marinated Partridge Or Grouse');
foods.push('Roasted Sharptail Grouse, Ptarmigan, Or Prairie Chicken');
foods.push('Spicy Maple-Roasted Quail');
foods.push('Roasted Small Game Birds');
foods.push('Wine-Braised Small Game Birds');
foods.push('Skewered Small Birds');
foods.push('Doves And Noodles');
foods.push('Small Birds In Rosemary Cream Sauce');
foods.push('Sautéed Chicken Livers');
foods.push('Fried Chicken Livers');
foods.push('Chicken Yakitori');
foods.push('Crispy Chicken Skins');
foods.push('Gizzard Confit');
foods.push('Pan-Seared Foie Gras');
foods.push('Foie Gras Terrine');
foods.push('Lardoons');
foods.push('Making A Jus');
foods.push('Roast Beef');
foods.push('Slow-Roasted Beef');
foods.push('Pan-Roasted Beef');
foods.push('Stuffed Eye Of Round Or Top Round Roast');
foods.push('Beef Wellington');
foods.push('Chuck Roast In Foil');
foods.push('Grilled Beef Roast');
foods.push('Grilled Or Broiled Steak');
foods.push('Carne Asada');
foods.push('Steak Fajitas');
foods.push('Kalbi (Korean Grilled Short Ribs)');
foods.push('Beef Kebabs');
foods.push('London Broil');
foods.push('Pan-Seared Steak');
foods.push('Sautéed Steak');
foods.push('Steak Diane');
foods.push('Steak Au Poivre (Peppered Steak With Cream Sauce)');
foods.push('Chicken-Fried Steak');
foods.push('Beef And Broccoli Stir-Fry');
foods.push('Sukiyaki');
foods.push('Becker Mongolian Beef');
foods.push('Beef Stroganoff');
foods.push('Beef Pot Roast');
foods.push('Stracotto (Italian Pot Roast)');
foods.push('Sauerbraten');
foods.push('Beef Stew');
foods.push('Boeuf Bourguignon');
foods.push('Carbonnade Flamande (Belgian Beef And Beer Stew)');
foods.push('Hearty Beef Ragu');
foods.push('Beef Rendang (Indonesian Dry Curry)');
foods.push('Hungarian Goulash (Pörkölt)');
foods.push('Guyanese Pepperpot');
foods.push('Beef Massaman Curry');
foods.push('Chili Con Carne');
foods.push('Sweet-And-Sour Brisket');
foods.push('Smoked Brisket');
foods.push('Smoked Beef Ribs');
foods.push('Brunswick Stew');
foods.push('Beef Braciole');
foods.push('Ropa Vieja (Cuban Braised And Shredded Beef)');
foods.push('Braised Short Ribs');
foods.push('Flank Steak With Dressing');
foods.push('Corned Beef');
foods.push('Corned Beef Hash');
foods.push('Slow-Roasted Veal');
foods.push('Stuffed Roasted Veal Breast');
foods.push('Grilled Or Broiled Veal Chops');
foods.push('Sautéed Veal Chops');
foods.push('Sautéed Veal Cutlets Or Scaloppine');
foods.push('Veal Piccata');
foods.push('Wienerschnitzel (Breaded Veal Cutlets)');
foods.push('Veal Parmigiana');
foods.push('Veal Saltimbocca');
foods.push('Paprika Schnitzel');
foods.push('Osso Buco (Braised Veal Shanks)');
foods.push('Roast Leg Of Lamb');
foods.push('Roasted Lamb Shoulder');
foods.push('Stuffed Lamb Roast');
foods.push('Pan-Roasted Rack Of Lamb');
foods.push('Pan-Roasted Loin Of Lamb');
foods.push('Grilled Or Broiled Butterflied Leg Of Lamb');
foods.push('Grilled Or Broiled Lamb Chops');
foods.push('Grilled Rack Of Lamb');
foods.push('Sautéed Lamb Chops');
foods.push('Lamb Shawarma');
foods.push('Lamb Kebabs');
foods.push('Braised Lamb Shoulder');
foods.push('Braised Lamb Shoulder Or Neck Chops');
foods.push('Braised Lamb Shanks With Chickpeas');
foods.push('Navarin Printanière (Spring Lamb Stew)');
foods.push('Irish Stew');
foods.push('Lamb Curry With Tomato');
foods.push('Lamb Saag (Curried Lamb And Greens)');
foods.push('Kentucky-Style Smoked Mutton Shoulder');
foods.push('Jamaican Curried Goat');
foods.push('Goat Birria');
foods.push('Pork Loin Roast');
foods.push('Herbed Pork Shoulder Roast');
foods.push('Pan-Roasted Pork Tenderloin');
foods.push('Crown Roast Of Pork');
foods.push('Crispy Pan-Roasted Pork Belly');
foods.push('Baked Pork Ribs');
foods.push('Latin Roasted Picnic Shoulder');
foods.push('Roast Fresh Ham Or Leg Of Pork');
foods.push('Roast Suckling Pig');
foods.push('Becker Pork Hash');
foods.push('Grilled Pork Tenderloin');
foods.push('Grilled Or Broiled Pork Loin Chops');
foods.push('Pork Souvlaki');
foods.push('Grilled Vietnamese-Style Pork');
foods.push('Sautéed Pork Chops');
foods.push('Breaded Pork Chops Or Cutlets');
foods.push('Sweet-And-Sour Pork');
foods.push('Country-Fried Pork Tenderloin With Gravy');
foods.push('Pork Braised In Milk');
foods.push('Braised Stuffed Pork Chops Cockaigne');
foods.push('Braised Pork With Sauerkraut');
foods.push('Braised Pulled Pork');
foods.push('Braised Carnitas');
foods.push('Pork Adovada');
foods.push('Smothered Country-Style Ribs');
foods.push('Chashu Pork (Japanese Braised Pork Belly)');
foods.push('Smoked Pork Shoulder');
foods.push('Barbecued Pork Ribs');
foods.push('Cooking Bacon');
foods.push('Baked Ham');
foods.push('Baked Country Ham');
foods.push('Broiled Ham Steak');
foods.push('Country Ham Steak With Red-Eye Gravy');
foods.push('Macleid’S Rockcastle Chili');
foods.push('Cincinnati Chili Cockaigne');
foods.push('Ohio Farmhouse Sausage Chili');
foods.push('Spiced Ground Meat For Tacos');
foods.push('Picadillo');
foods.push('Keema Alu (Indian Spiced Beef With Potatoes And Spices)');
foods.push('Adana-Style Lamb Kebabs');
foods.push('Hamburger Patties');
foods.push('Becker Burgers');
foods.push('Becker Lamb Patties');
foods.push('Beet And Caper Burgers');
foods.push('Meatloaf');
foods.push('Additions To Meatloaf');
foods.push('Shepherd’S Pie');
foods.push('Hamburger Pie');
foods.push('Königsberger Klops (German Meatballs)');
foods.push('Italian Meatballs');
foods.push('Swedish Meatballs');
foods.push('Cooking Sausage Links');
foods.push('Country Sausage');
foods.push('Fresh Chorizo Sausage');
foods.push('Italian Sausage');
foods.push('Merguez Sausage');
foods.push('Bratwurst');
foods.push('Boudin Blanc (French White Sausage)');
foods.push('Grapes And Sausages');
foods.push('Pork Scrapple Or Goetta');
foods.push('Pâté De Campagne');
foods.push('Pork Rillettes');
foods.push('Sautéed Calf’S Liver');
foods.push('Pan-Fried Sweetbreads');
foods.push('Sautéed Kidneys With Mustard');
foods.push('Crispy Pan-Fried Tongue With Onions And Jalapeños');
foods.push('Anticuchos De Corazón (Peruvian Beef Heart Skewers)');
foods.push('Fried Tripe');
foods.push('Italian-Style Tripe');
foods.push('Stewed Chitterlings Or Hog Maws');
foods.push('Sautéed Chitterlings');
foods.push('Braised Oxtails (Oxtail Stew)');
foods.push('Pork Rinds Or Chicharrones');
foods.push('Fried Rabbit');
foods.push('Fricassee Of Rabbit');
foods.push('Hasenpfeffer');
foods.push('Braised Marinated Rabbit With Prunes');
foods.push('Lapin À La Moutarde (Rabbit With Mustard)');
foods.push('Roasted Venison');
foods.push('Venison Pot Roast');
foods.push('Sautéed Venison Steaks');
foods.push('Venison Burger');
foods.push('Becker Venison Medallions');
foods.push('Braised Bear');
foods.push('Buffalo Roast With Bourbon-Molasses Glaze');
foods.push('Basic Bread Stuffing Or Dressing');
foods.push('Basic Corn Bread Stuffing Or Dressing');
foods.push('Additions To Bread Stuffing');
foods.push('Apple And Cherry Bread Stuffing');
foods.push('Corn Bread Stuffing With Roasted Peppers');
foods.push('Apple And Prune Dressing');
foods.push('Italian Bread Crumb Stuffing');
foods.push('Parsley And Bread Crumb Stuffing');
foods.push('Bacon Stuffing For Fish');
foods.push('Seafood Stuffing');
foods.push('Green Herb Stuffing');
foods.push('Sausage, Onion, And Sage Stuffing');
foods.push('Spinach-Ricotta Stuffing');
foods.push('Couscous Stuffing With Apricots And Pistachios');
foods.push('Rice Dressing With Chorizo And Chiles');
foods.push('Spiced Rice Stuffing');
foods.push('Wild Rice Dressing');
foods.push('Sauerkraut Stuffing For Wildfowl');
foods.push('Chicken Rice Casserole');
foods.push('Chicken Tamale Pie');
foods.push('Corn Bread Tamale Pie');
foods.push('King Ranch Chicken Casserole');
foods.push('Tuna-Vegetable Casserole');
foods.push('Turkey Tetrazzini');
foods.push('Chicken Enchiladas');
foods.push('Cheese Enchiladas');
foods.push('Beef Or Pork Enchiladas');
foods.push('Enchiladas Verdes');
foods.push('New Mexico–Style Enchilada Stacks');
foods.push('Basic Pan Gravy');
foods.push('Quick Pan Sauce Or Gravy');
foods.push('Turkey Giblet Gravy');
foods.push('Herb Pan Sauce');
foods.push('Sweet-Sour Orange Pan Sauce');
foods.push('Wine And Sour Cherry Pan Sauce');
foods.push('Sausage Gravy');
foods.push('Mushroom Gravy');
foods.push('White Sauce Or Béchamel');
foods.push('Additions To White Sauce');
foods.push('Vegan White Sauce Or Béchamel');
foods.push('Sauce Mornay (Cheese Sauce)');
foods.push('Sauce Soubise (Onion Sauce)');
foods.push('Sauce Velouté');
foods.push('Sauce Suprême (Enriched Velouté)');
foods.push('White Wine Sauce');
foods.push('Sauce Ravigote');
foods.push('Sauce Allemande (Egg-Thickened Velouté)');
foods.push('Sauce Espagnole (Brown Sauce)');
foods.push('Quick Brown Sauce');
foods.push('Sauce Demi-Glace');
foods.push('Sauce Madeira');
foods.push('Sauce Lyonnaise (Brown Onion Sauce)');
foods.push('Sauce Chasseur (Hunter’S Sauce)');
foods.push('Sauce Marchand De Vin (Red Wine Sauce)');
foods.push('Basic Cream Sauce');
foods.push('Avgolemono (Greek Lemon-Egg Sauce)');
foods.push('Stir-Fry Sauce');
foods.push('Wine Plum Sauce');
foods.push('Fig And Red Wine Sauce');
foods.push('Quick Orange Sauce For Duck');
foods.push('Sauce Meurette (Burgundian Red Wine Sauce)');
foods.push('Mole Poblano (Red Mole)');
foods.push('Green Mole');
foods.push('New Mexico–Style Chile Sauce');
foods.push('Roasted Red Pepper Sauce');
foods.push('Roasted Tomatillo Spinach Sauce');
foods.push('Tomato Sauce');
foods.push('Marinara Sauce');
foods.push('Pizza Sauce');
foods.push('No-Cook Tomato Sauce');
foods.push('Grilled Tomato Sauce');
foods.push('Veracruz-Style Tomato Sauce');
foods.push('Amatriciana Sauce');
foods.push('Puttanesca Sauce');
foods.push('Meaty Tomato Sauce');
foods.push('Bolognese Sauce');
foods.push('Tomato Sauce With Meatballs');
foods.push('Brown Butter');
foods.push('Black Butter');
foods.push('Beurre Blanc (White Butter Sauce)');
foods.push('Variations Of Beurre Blanc');
foods.push('Miso Beurre Blanc');
foods.push('Additions To Flavored Butter');
foods.push('Lemon And Parsley Butter');
foods.push('Snail Butter');
foods.push('Montpellier Butter');
foods.push('Shrimp Or Lobster Butter');
foods.push('Kimchi Butter');
foods.push('Chile Butter');
foods.push('Green Butter');
foods.push('Hollandaise');
foods.push('Blender Hollandaise');
foods.push('Béarnaise Sauce');
foods.push('Blender Béarnaise Sauce');
foods.push('Mayonnaise');
foods.push('Blender Mayonnaise');
foods.push('Additions To Mayonnaise');
foods.push('Sauce Parisienne (Eggless Mayonnaise)');
foods.push('Tartar Sauce');
foods.push('Sauce Louis');
foods.push('Rémoulade Sauce');
foods.push('Creole Rémoulade Sauce');
foods.push('Tonnato Sauce (Tuna Sauce)');
foods.push('Aïoli (Garlic Mayonnaise)');
foods.push('Skordalia (Potato-Garlic Mayonnaise)');
foods.push('Rouille (Red Pepper–Garlic Mayonnaise)');
foods.push('Quick Ketchup');
foods.push('Gastrique (Sweet-Sour Vinegar Sauce)');
foods.push('Sweet-And-Sour Sauce');
foods.push('Tamarind Chutney');
foods.push('English Cumberland Sauce');
foods.push('Horseradish Sauce');
foods.push('Honey Mustard Dipping Sauce');
foods.push('Scandinavian Mustard-Dill Sauce');
foods.push('Bavarian Apple And Horseradish Sauce');
foods.push('Mojo');
foods.push('Mint Sauce');
foods.push('Chimichurri');
foods.push('Salsa Verde (Italian Green Sauce)');
foods.push('Zhug (Yemeni Cilantro-Chile Sauce)');
foods.push('Cilantro-Mint Chutney');
foods.push('Sauce Gribiche');
foods.push('Corn And Tomato Relish');
foods.push('Tomato-Olive Relish');
foods.push('Red Onion Marmalade');
foods.push('Tzatziki (Greek Yogurt Sauce)');
foods.push('Yogurt-Dill Sauce');
foods.push('Raita (Indian Yogurt Salad)');
foods.push('Tomato Achar');
foods.push('Becker Cocktail Sauce');
foods.push('Z.26 Steak Sauce');
foods.push('Mignonette Sauce');
foods.push('Champagne Mignonette');
foods.push('Mignonette Granité');
foods.push('Garlic And Walnut Sauce');
foods.push('Jen’S Basil Oil');
foods.push('Romesco Sauce');
foods.push('Habanero-Citrus Hot Sauce');
foods.push('Nam Prik (Thai-Style Relish)');
foods.push('Peanut Dipping Sauce');
foods.push('Nuoc Cham');
foods.push('Chile-Infused Fish Sauce');
foods.push('Ssamjang (Korean Dipping Sauce)');
foods.push('Tentsuyu (Tempura Dipping Sauce)');
foods.push('Katsu Sauce');
foods.push('Dipping Sauce For Dumplings');
foods.push('Spicy Chinese Chile Crisp');
foods.push('Sriracha');
foods.push('Chinese Black Bean Sauce');
foods.push('Pico De Gallo (Fresh Salsa)');
foods.push('Salsa Verde Cruda (Raw Tomatillo Salsa)');
foods.push('Table Salsa');
foods.push('Corn, Tomato, And Avocado Salsa');
foods.push('Guasacaca Sauce (Venezuelan Avocado Salsa)');
foods.push('Roasted Tomato–Chipotle Salsa');
foods.push('Fruit Salsa');
foods.push('Vinaigrette');
foods.push('Additions To Vinaigrette');
foods.push('Megan’S Lemon-Dijon Dressing');
foods.push('Walnut Vinaigrette');
foods.push('Poppy Seed–Honey Dressing');
foods.push('Roasted Red Pepper Dressing');
foods.push('Japanese Steakhouse Ginger Dressing');
foods.push('Roasted Garlic Dressing');
foods.push('Miso Dressing');
foods.push('Tahini Dressing');
foods.push('Russian Dressing');
foods.push('Thousand Island Dressing');
foods.push('Ranch Dressing');
foods.push('Green Goddess Dressing');
foods.push('Herbed Yogurt Dressing');
foods.push('Creamy Blue Cheese Dressing');
foods.push('Feta Or Goat Cheese Dressing');
foods.push('Buttermilk-Honey Dressing');
foods.push('Creamy Horseradish Dressing');
foods.push('Creamy Parmesan Dressing');
foods.push('Vietnamese Caramel Sauce');
foods.push('Hoisin-Ginger Glaze');
foods.push('Brown Sugar Glaze');
foods.push('Cranberry Glaze');
foods.push('Marmalade Glaze');
foods.push('Pineapple Glaze');
foods.push('Bourbon-Molasses Glaze');
foods.push('Honey Glaze');
foods.push('Lemon Marinade');
foods.push('Wine Marinade');
foods.push('Tandoori Marinade');
foods.push('Buttermilk Marinade');
foods.push('Balkan Marinade');
foods.push('Sinaloan Marinade');
foods.push('Thai-Style Lemongrass Marinade');
foods.push('Vietnamese-Style Marinade');
foods.push('Beer Marinade');
foods.push('Becker Chicken Or Pork Marinade');
foods.push('Teriyaki Marinade');
foods.push('Kansas City Barbecue Sauce');
foods.push('Chipotle Barbecue Sauce');
foods.push('Alabama White Barbecue Sauce');
foods.push('South Carolina–Style Mustard Barbecue Sauce');
foods.push('North Carolina–Style Barbecue Sauce');
foods.push('Kentucky-Style Mutton Dip');
foods.push('Basic Mop');
foods.push('Beer Mop');
foods.push('Jamaican Jerk Paste');
foods.push('Mediterranean Garlic Herb Paste');
foods.push('Mustard Paste');
foods.push('Harissa');
foods.push('Mexican Adobo');
foods.push('Green Curry Paste');
foods.push('Red Curry Paste');
foods.push('Massaman Curry Paste');
foods.push('Charmoula (Moroccan Herb Paste)');
foods.push('Pesto And Pistou');
foods.push('Spicy Carrot Top Pesto');
foods.push('Sun-Dried Tomato Pesto');
foods.push('Persillade');
foods.push('Gremolata');
foods.push('Garlic-Herb Rub For Poultry');
foods.push('Cajun Blackening Spice');
foods.push('Southern Barbecue Dry Rub');
foods.push('Coffee Spice Rub');
foods.push('Sweet And Smoky Spice Rub');
foods.push('Jerk Spice Rub');
foods.push('Chesapeake Bay Seasoning');
foods.push('Chili Powder');
foods.push('Madras Curry Powder');
foods.push('Garam Masala');
foods.push('Chaat Masala');
foods.push('Baharat');
foods.push('Dukkah');
foods.push('Za’Atar');
foods.push('Berbere');
foods.push('Everything Seasoning');
foods.push('Ras El Hanout');
foods.push('Five-Spice Powder');
foods.push('Sichuan Pepper Salt');
foods.push('Quatre Épices (Spice Parisienne)');
foods.push('White Bread');
foods.push('Whole Wheat Sandwich Bread');
foods.push('Sprouted Whole Wheat Bread');
foods.push('Cinnamon Raisin Bread');
foods.push('Pimiento Cheese Bread');
foods.push('Dill Batter Loaf');
foods.push('All Whole Wheat Bread Cockaigne');
foods.push('Limpa (Swedish Rye Bread)');
foods.push('Cracked-Wheat Bread');
foods.push('Oat Bread Cockaigne');
foods.push('English Muffin Bread');
foods.push('Buttermilk Potato Bread');
foods.push('Challah');
foods.push('Brioche');
foods.push('Chocolate-Walnut Babka');
foods.push('Quick French Bread');
foods.push('Ciabatta');
foods.push('Gluten-Free Sandwich Bread');
foods.push('Gluten-Free Whole-Grain Bread');
foods.push('Rustic French Bread');
foods.push('Fougasse');
foods.push('White Bread Made With A Sponge Starter');
foods.push('Rye Bread With A Sponge Starter');
foods.push('Molasses Bread');
foods.push('Sourdough Starter (Levain)');
foods.push('Rustic No-Knead Sourdough Bread');
foods.push('Sourdough Rye Bread');
foods.push('Pita Bread');
foods.push('Naan');
foods.push('Layered Paratha');
foods.push('Lefse');
foods.push('Flour Tortillas');
foods.push('Corn Tortillas');
foods.push('Sopes');
foods.push('Arepas');
foods.push('Focaccia');
foods.push('Khachapuri (Georgian Cheese-Filled Bread)');
foods.push('Pizza Dough');
foods.push('Pizza Margherita (Pizza With Tomato Sauce And Mozzarella)');
foods.push('Gluten-Free Pizza');
foods.push('Chicago-Style Deep-Dish Pizza');
foods.push('Grandma-Style Pan Pizza');
foods.push('Grilled Pizza');
foods.push('Parker House Rolls');
foods.push('Cloverleaf Rolls');
foods.push('No-Knead Refrigerator Rolls');
foods.push('Buttermilk Rolls (Fan-Tans)');
foods.push('Buttermilk Potato Rolls');
foods.push('Cheese Rolls');
foods.push('Whole Wheat Rolls');
foods.push('Hard Rolls');
foods.push('Hamburger Buns');
foods.push('Hot Cross Buns');
foods.push('Palm Leaf Rolls (Sour Cream Rolls)');
foods.push('Kolaches');
foods.push('Overnight Sweet Crescent Rolls');
foods.push('Sticky Buns');
foods.push('Cinnamon Rolls');
foods.push('Brioche À Tête (Topped Brioche)');
foods.push('English Muffins');
foods.push('Crumpets');
foods.push('Bagels');
foods.push('Bialys');
foods.push('Pretzels');
foods.push('Yeasted Coffee Cake');
foods.push('Filled Coffee Cake');
foods.push('Danish Coffee Cake');
foods.push('Panettone (Italian Christmas Bread)');
foods.push('Stollen (German Christmas Loaf)');
foods.push('Kugelhopf');
foods.push('Date Nut Bread');
foods.push('Sally Lunn Bread');
foods.push('Orange Bread');
foods.push('Banana Bread Cockaigne');
foods.push('Marbled Banana Bread');
foods.push('Pumpkin Bread');
foods.push('Zucchini Bread');
foods.push('Lemon Brown Butter Loaf');
foods.push('Beer Bread');
foods.push('Beer, Cheese, And Scallion Bread');
foods.push('Rosemary-Olive Bread');
foods.push('Irish Soda Bread');
foods.push('Poppy Seed Loaf');
foods.push('Brown Bread');
foods.push('Quick Coffee Cake');
foods.push('Coffee Cake With Marbled Filling');
foods.push('Deluxe Crumb Cake');
foods.push('Deluxe Coconut Chocolate Chip Coffee Cake');
foods.push('Corn Bread, Corn Muffins, Or Corn Sticks');
foods.push('Buckwheat Corn Bread');
foods.push('Southern Corn Bread');
foods.push('Crackling Corn Bread');
foods.push('Megan’S Southern Corn Bread');
foods.push('Corn Zephyrs Cockaigne');
foods.push('Crusty Soft-Center Spoon Bread');
foods.push('Buttermilk Spoon Bread');
foods.push('Muffins');
foods.push('Sour Cream Muffins');
foods.push('Lemon–Poppy Seed Muffins');
foods.push('Pumpkin Or Sweet Potato Muffins');
foods.push('Blueberry Muffins');
foods.push('Double-Chocolate Muffins');
foods.push('Herb And Roasted Garlic Muffins');
foods.push('Bran Muffins');
foods.push('Sunrise Muffins');
foods.push('Apple-Walnut Muffins');
foods.push('Banana Muffins');
foods.push('Popovers');
foods.push('Cheese Popovers');
foods.push('Yorkshire Pudding');
foods.push('Buttermilk Biscuits');
foods.push('Angel Biscuits');
foods.push('Sweet Potato Biscuits');
foods.push('Cornmeal Biscuits');
foods.push('Whole-Grain Biscuits');
foods.push('Biscuit Sticks');
foods.push('Quick Drop Biscuits');
foods.push('Sticky Breakfast Pull-Apart Bread');
foods.push('Quick Cream Biscuits Or Shortcakes');
foods.push('Easter Bunny Biscuits');
foods.push('Griddle Biscuits');
foods.push('Megan’S Cheddar-Scallion Biscuits');
foods.push('Beaten Biscuits');
foods.push('Classic Scones');
foods.push('Lemon-Blueberry Scones');
foods.push('Chocolate-Orange Scones');
foods.push('Croutons');
foods.push('Garlic Bread');
foods.push('Melba Toast');
foods.push('Pancakes Or Griddle Cakes');
foods.push('Buttermilk Pancakes');
foods.push('Buckwheat Pancakes');
foods.push('Additions To Pancakes');
foods.push('Yeasted Pancakes');
foods.push('Four-Grain Flapjacks');
foods.push('Cornmeal Pancakes');
foods.push('Johnnycakes');
foods.push('Buckwheat Blini');
foods.push('Oatmeal Pancakes');
foods.push('Lemon–Sour Cream Pancakes');
foods.push('Cottage Cheese Pancakes');
foods.push('Waffles');
foods.push('Buttermilk Waffles');
foods.push('Cornmeal Waffles');
foods.push('Bacon Cornmeal Waffles');
foods.push('Chocolate Waffles');
foods.push('Golden Sweet Potato Waffles');
foods.push('Yeasted Belgian Waffles');
foods.push('Liège-Style Waffles');
foods.push('French Toast');
foods.push('Savory French Toast');
foods.push('Stuffed French Toast');
foods.push('Baked French Toast');
foods.push('Bostock');
foods.push('Savory Or Sweet Crêpes');
foods.push('Buckwheat Crêpes');
foods.push('Filled Savory Crêpes');
foods.push('Filled Sweet Crêpes');
foods.push('Crêpes Suzette');
foods.push('Crêpes With Caramelized Apples');
foods.push('Crêpe Cake');
foods.push('Blintzes');
foods.push('Sweet Cheese Blintzes');
foods.push('Blueberry Blintzes');
foods.push('Palatschinken (Viennese-Style Crêpes)');
foods.push('Dosas (Indian Rice And Lentil Pancakes)');
foods.push('Bánh Xèo (Savory Vietnamese Filled Crêpes)');
foods.push('Dutch Baby');
foods.push('Pfannkuchen (German Pancake)');
foods.push('Nöckerl (Austrian Pancakes)');
foods.push('Socca (Savory Chickpea Pancake)');
foods.push('Cake Doughnuts');
foods.push('Yeast Doughnuts');
foods.push('Sour Cream Doughnuts');
foods.push('Buttermilk Potato Doughnuts');
foods.push('Chocolate Doughnuts');
foods.push('Dropped Doughnuts');
foods.push('Jelly Doughnuts');
foods.push('Honey-Dipped Doughnuts');
foods.push('Crullers');
foods.push('New Orleans Beignets');
foods.push('Calas (Creole Rice Fritters)');
foods.push('Pets De Nonne (French-Style Beignets)');
foods.push('Rosettes');
foods.push('Sopapillas');
foods.push('Corn And Ham Fritters');
foods.push('Hushpuppies');
foods.push('Cheese Croquettes Cockaigne');
foods.push('Salt Cod Croquettes');
foods.push('Salmon Croquettes');
foods.push('Fritter Batter For Fruit');
foods.push('Apple Fritters');
foods.push('Beer Batter');
foods.push('Tempura Batter');
foods.push('Pakora Batter');
foods.push('Cornstarch Batter');
foods.push('Fritto Misto');
foods.push('Flour Coating');
foods.push('Bound Bread Crumb Or Cracker Coating');
foods.push('Seasoned Crumbs');
foods.push('Additions To Pie Dough');
foods.push('Basic Pie Or Pastry Dough');
foods.push('All-Butter Pie Or Pastry Dough');
foods.push('Cheddar Pie Or Pastry Dough');
foods.push('Cornmeal Pie Or Pastry Dough');
foods.push('Nutty Pie Or Pastry Dough');
foods.push('Whole-Grain Pie Or Pastry Dough');
foods.push('Sweet Dough For Tarts');
foods.push('Cream Cheese Pastry Dough');
foods.push('Phyllo Pie Crust');
foods.push('Meringue Pie Shell');
foods.push('Pat-In-The-Pan Butter Dough');
foods.push('Pat-In-The-Pan Shortbread Dough');
foods.push('Crumb Crust');
foods.push('Cornflake Pie Crust');
foods.push('Nut Crust');
foods.push('Coconut Crust');
foods.push('Fresh Berry Pie');
foods.push('Berry Or Cherry Pie With Canned Or Bottled Fruit');
foods.push('Blueberry Pie');
foods.push('Fresh Cherry Pie');
foods.push('Glazed Berry Pie');
foods.push('Apple Pie');
foods.push('Peach Custard Pie Cockaigne');
foods.push('Peach Pie');
foods.push('Strawberry Rhubarb Pie');
foods.push('Concord Grape Pie');
foods.push('Mincemeat Pie');
foods.push('Raisin Pie');
foods.push('Deep-Dish Fruit Pie');
foods.push('Fruit Slab Pie');
foods.push('Tarte Tatin');
foods.push('Sour Cream Cherry Or Berry Pie Or Tartlets');
foods.push('Bittersweet Chocolate Tart');
foods.push('Chocolate-Glazed Caramel Tart');
foods.push('Salted Caramel Nut Tart');
foods.push('Lemon Tart');
foods.push('Fresh Fruit Tart');
foods.push('Raspberry Streusel Tart');
foods.push('Apple Tartlets');
foods.push('Linzertorte');
foods.push('Bakewell Tart');
foods.push('Megan’S Frangipane Fruit Tarts');
foods.push('Pecan Pie');
foods.push('Transparent Pie');
foods.push('Chocolate Chip Or Chunk Pecan Pie');
foods.push('Shoofly Pie');
foods.push('Chess Pie');
foods.push('Chocolate Chess Pie');
foods.push('Pumpkin Or Squash Chess Pie');
foods.push('Angostura Chess Pie');
foods.push('Lemon Chess Pie');
foods.push('Chess Tartlets');
foods.push('Honey, Sorghum, Or Maple Syrup Pie');
foods.push('Custard Pie');
foods.push('Jam Custard Pie');
foods.push('Chocolate-Glazed Custard Pie');
foods.push('Vanilla Cream Pie');
foods.push('Coffee Cream Pie');
foods.push('Chocolate Cream Pie');
foods.push('Banana Cream Pie');
foods.push('Butterscotch Cream Pie');
foods.push('Coconut Cream Pie');
foods.push('Pumpkin, Squash, Or Sweet Potato Pie');
foods.push('Lemon Meringue Pie');
foods.push('Ohio Shaker Lemon Pie');
foods.push('Key Lime Pie');
foods.push('No-Bake Lemon Or Lime Pie');
foods.push('Lemon Or Lime Chiffon Pie');
foods.push('Black Bottom Pie');
foods.push('Pumpkin Chiffon Pie');
foods.push('Peanut Butter Pie');
foods.push('Blueberry And Peach Buckle');
foods.push('Fruit Crisp');
foods.push('Ginger Crisp');
foods.push('Strawberry Sonker');
foods.push('Sour Cherry Amaretti Crisp');
foods.push('Apple, Peach, Or Apricot Brown Betty');
foods.push('Fruit Cobbler');
foods.push('Chocolate Cobbler');
foods.push('Apricot-Cherry Slump');
foods.push('Blackberry-Raspberry Grunt');
foods.push('Apple Or Pear Pandowdy');
foods.push('Berry Pandowdy');
foods.push('Cherry Clafoutis');
foods.push('Far Breton');
foods.push('Apple Dumplings');
foods.push('Sweet Fruit Turnovers');
foods.push('Apple Or Pear Turnovers');
foods.push('Treva’S Fried Apple Pies');
foods.push('Fruit Galette Or Crostata');
foods.push('Apple Galette Or Crostata');
foods.push('Puff Pastry');
foods.push('Chocolate Puff Pastry');
foods.push('Rough Puff Pastry');
foods.push('Palmiers');
foods.push('Patty Shells');
foods.push('Mille-Feuille (Napoleon)');
foods.push('Croissants');
foods.push('Raspberry Croissants');
foods.push('Almond Croissants');
foods.push('Pain Au Chocolat');
foods.push('Kouign Amann');
foods.push('Danish Pastry Dough');
foods.push('Bear Claws');
foods.push('Choux Paste');
foods.push('Cream Puffs');
foods.push('Chocolate Éclairs');
foods.push('Profiteroles');
foods.push('Croquembouche');
foods.push('Paris-Brest');
foods.push('Apple Strudel');
foods.push('Baklava');
foods.push('Phyllo Cups');
foods.push('Phyllo Napoleons');
foods.push('Cornish Pasties');
foods.push('Empanadas With Picadillo');
foods.push('Fatayer Bi Sabanekh (Lebanese Spinach Pies)');
foods.push('Piroshki');
foods.push('Potato Knishes');
foods.push('Savory Cabbage Strudel');
foods.push('Beef Potpie');
foods.push('Chicken Or Turkey Potpie');
foods.push('Crawfish Pie');
foods.push('Steak And Kidney Pie');
foods.push('Tourtière (French Canadian Meat Pie)');
foods.push('Spanakopita (Greek Spinach Pie)');
foods.push('Tomato Cobbler');
foods.push('Tomato-Ricotta Tart');
foods.push('Calzones');
foods.push('Stromboli');
foods.push('Angel Food Cake');
foods.push('Coffee Angel Food Cake');
foods.push('Coconut Angel Food Cake');
foods.push('Lemon Or Orange Angel Food Cake');
foods.push('Chocolate Angel Food Cake');
foods.push('Marble Angel Food Cake');
foods.push('Sponge Cake');
foods.push('Passover Citrus Sponge Cake');
foods.push('Passover Nut Sponge Cake');
foods.push('Chocolate Sponge Cake');
foods.push('Tres Leches Cake');
foods.push('French Sponge Cake (Biscuit)');
foods.push('Génoise');
foods.push('Chocolate Génoise');
foods.push('Chiffon Cake');
foods.push('Orange Chiffon Cake');
foods.push('Mocha Chiffon Cake');
foods.push('White Cake');
foods.push('Confetti Cake');
foods.push('Lemon Coconut Layer Cake');
foods.push('Coconut Milk Cake Cockaigne');
foods.push('Buttermilk Layer Cake');
foods.push('Red Velvet Cake');
foods.push('Four-Egg Yellow Cake');
foods.push('Eight-Yolk Gold Cake');
foods.push('Fresh Fruit Kuchen');
foods.push('Poppy Seed Custard Cake Cockaigne');
foods.push('Pound Cake');
foods.push('Liquor-Soaked Pound Cake');
foods.push('Mimosa Pound Cake');
foods.push('Chocolate Pound Cake');
foods.push('Lemon–Poppy Seed Pound Cake');
foods.push('Sour Cream Pound Cake');
foods.push('The Rombauer Special Chocolate Cake');
foods.push('Devil’S Food Cake Cockaigne');
foods.push('Chocolate Coconut Icebox Cake');
foods.push('Chocolate Blackout Cake');
foods.push('Chocolate Mayonnaise Cake');
foods.push('Sourdough Chocolate Cake');
foods.push('German Chocolate Cake');
foods.push('Marzipan Cake');
foods.push('Velvet Spice Bundt Cake');
foods.push('Burnt Sugar Cake');
foods.push('Fig And Brown Butter Spice Cake');
foods.push('Applesauce Cake');
foods.push('Rombauer Jam Cake');
foods.push('Oatmeal Cake');
foods.push('Tomato Soup Cake (Mystery Cake)');
foods.push('Banana Cake Cockaigne');
foods.push('St. Louis Gooey Butter Cake');
foods.push('Blitzkuchen (Lightning Cake)');
foods.push('French Yogurt Cake');
foods.push('Chocolate Sheet Cake (Texas Sheet Cake)');
foods.push('Mississippi Mud Cake');
foods.push('Vegan Chocolate Cake');
foods.push('Olive Oil Cake');
foods.push('Orange Rum Cake');
foods.push('Orange Almond Cake');
foods.push('Vegan Orange Cake');
foods.push('Apple Cake');
foods.push('Carrot Cake');
foods.push('Hummingbird Cake');
foods.push('Fresh Ginger Cake');
foods.push('Apple Stack Cake');
foods.push('Apple, Peach, Or Plum Cake Cockaigne');
foods.push('Pineapple Upside-Down Cake');
foods.push('Guy Fawkes Day Cake');
foods.push('Lekach (Jewish Honey Cake)');
foods.push('Bienenstich (Bee Sting Cake)');
foods.push('Fruitcake Cockaigne');
foods.push('Dark Fruitcake');
foods.push('Almond Torte Cockaigne');
foods.push('Passover Almond Torte');
foods.push('Hazelnut Torte');
foods.push('Chocolate Walnut Torte');
foods.push('Sachertorte');
foods.push('Individual Molten Chocolate Cakes');
foods.push('Flourless Chocolate Decadence');
foods.push('Chocolate Mousse Cake');
foods.push('Sicilian Cassata');
foods.push('Boston Cream Pie');
foods.push('Black Forest Cake');
foods.push('Chocolate Raspberry Cream Cake');
foods.push('Icebox Cake');
foods.push('Savarin');
foods.push('Baba Au Rhum');
foods.push('Cake Sheet For Roll Cakes');
foods.push('Sponge Cake Sheet');
foods.push('Jelly Roll');
foods.push('Cream Roll');
foods.push('Lemon Roll');
foods.push('Chocolate-Filled Roll');
foods.push('Bûche De Noël (Yule Log Cake)');
foods.push('Petits Fours');
foods.push('Madeleines');
foods.push('Cannelés De Bordeaux');
foods.push('Financiers');
foods.push('Ladyfingers');
foods.push('Baked Meringue');
foods.push('Dacquoise');
foods.push('Meringue Mushrooms');
foods.push('Fresh Strawberry Meringue Or Dacquoise');
foods.push('Additions To Cheesecake');
foods.push('Cheesecake Cockaigne');
foods.push('New York–Style Cheesecake');
foods.push('Creamy Water-Bath Cheesecake');
foods.push('Chocolate Cheesecake');
foods.push('Pumpkin Cheesecake');
foods.push('High-Altitude Classic 1-2-3-4 Cake (Or Cupcakes)');
foods.push('High-Altitude Angel Food Cake');
foods.push('High-Altitude Chocolate Angel Food Cake');
foods.push('High-Altitude White Cake');
foods.push('High-Altitude Fudge Cake');
foods.push('High-Altitude Citrus Sponge Cake');
foods.push('High-Altitude Carrot Cake');
foods.push('High Altitude Peach-Pecan Upside-Down Cake');
foods.push('High-Altitude Sour Cream Streusel Coffee Cake');
foods.push('High-Altitude Gingerbread');
foods.push('High-Altitude Chocolate Sponge Roll');
foods.push('Brownies Cockaigne');
foods.push('Fudgy Brownies');
foods.push('Cheesecake Brownies');
foods.push('Butterscotch Brownies Or Blondies');
foods.push('Chocolate-Glazed Toffee Bars');
foods.push('Christmas Chocolate Bars Cockaigne');
foods.push('Gooey Chocolate Oat Bars');
foods.push('Raspberry Streusel Bars');
foods.push('Pecan Or Angel Slices');
foods.push('Nanaimo Bars');
foods.push('Pb&J Bars');
foods.push('Lemon Bars');
foods.push('Lebkuchen (German Honey Bars)');
foods.push('Soft And Chewy Sugar Cookies');
foods.push('Chewy Chocolate Sugar Cookies');
foods.push('Double-Chocolate Peppermint Cookies');
foods.push('Crunchy Sugar Cookies');
foods.push('Snickerdoodles');
foods.push('Chocolate Chip Cookies');
foods.push('Skillet Chocolate Chip Cookie');
foods.push('Nora’S Chocolate Chip Cookies');
foods.push('White Chocolate Macadamia Cookies');
foods.push('Chocolate Krinkles');
foods.push('Peanut Butter Cookies');
foods.push('Oatmeal Raisin Cookies');
foods.push('Cowboy Cookies');
foods.push('Anzac Biscuits');
foods.push('Gingersnaps');
foods.push('Pfeffernüsse (Peppernuts)');
foods.push('Hermits');
foods.push('Mexican Wedding Cakes');
foods.push('Benne (Sesame Seed) Wafers');
foods.push('Pecan Lace');
foods.push('Oatmeal Lace Cookies');
foods.push('Lemony Butter Wafers');
foods.push('Florentines Cockaigne');
foods.push('Ginger Thins');
foods.push('Almond Macaroons');
foods.push('Coconut Macaroons');
foods.push('Chocolate Coconut Macaroons');
foods.push('Meringue Kisses');
foods.push('Rolled Sugar Cookies');
foods.push('Sand Tarts');
foods.push('Moravian Molasses Thins');
foods.push('Gingerbread Men');
foods.push('Viennese Crescents');
foods.push('Mandelplättchen (Almond Pretzels)');
foods.push('Graham Crackers');
foods.push('Whole-Grain Seed Wafers');
foods.push('Anise-Almond Biscotti');
foods.push('Chocolate-Orange Biscotti');
foods.push('Zimsterne (Cinnamon-Almond Stars)');
foods.push('Springerle (Molded Anise Cookies)');
foods.push('Spekulatius');
foods.push('Spritz Cookies');
foods.push('Chocolate Spritz Cookies');
foods.push('Scotch Shortbread');
foods.push('Vanilla Icebox Cookies');
foods.push('Additions To Icebox Cookies');
foods.push('Pinwheel Icebox Cookies');
foods.push('Filled Cookies');
foods.push('Fillings For Filled Cookies');
foods.push('Alfajores De Dulce De Leche');
foods.push('Macarons');
foods.push('Flavored Macarons');
foods.push('Baci Di Dama (Chocolate-Filled Hazelnut Cookies)');
foods.push('Rugelach');
foods.push('Hamantaschen');
foods.push('Fig Keplers');
foods.push('Pecan Tassies');
foods.push('Jelly Tots');
foods.push('Quick Pb&J Thumbprints');
foods.push('Macaroon Jam Tarts');
foods.push('Linzer Hearts');
foods.push('Butter Krumkakes');
foods.push('Almond Krumkakes');
foods.push('Stroopwafels');
foods.push('Ice Cream Cones');
foods.push('Fortune Cookies');
foods.push('Brandy Snaps');
foods.push('Maple Curls');
foods.push('Tuiles (French Almond Wafers)');
foods.push('Gingerbread House');
foods.push('Whipped Cream');
foods.push('Stabilized Whipped Cream');
foods.push('Whipped Crème Fraîche');
foods.push('Additions To Whipped Cream');
foods.push('Quick Vanilla Butter Frosting');
foods.push('Quick Lemon Frosting');
foods.push('Quick Orange Frosting');
foods.push('Quick Mocha Frosting');
foods.push('Chocolate Fudge Frosting');
foods.push('Cream Cheese Frosting');
foods.push('Chocolate Cream Cheese Frosting');
foods.push('Peanut Butter Frosting');
foods.push('Salted Caramel Frosting');
foods.push('Chocolate Satin Frosting');
foods.push('Chocolate Sour Cream Frosting');
foods.push('White Chocolate Frosting');
foods.push('Chocolate Mousse Frosting');
foods.push('Vegan Chocolate Frosting');
foods.push('French Meringue');
foods.push('Swiss Meringue');
foods.push('Italian Meringue');
foods.push('Coffee-Flavored Meringue');
foods.push('Cocoa Meringue');
foods.push('Soft Meringue Topping');
foods.push('Fluffy White Frosting');
foods.push('Luscious Orange Icing');
foods.push('French Buttercream');
foods.push('Meringue Buttercream');
foods.push('Liquor-Flavored Buttercream');
foods.push('Coffee Buttercream');
foods.push('Mocha Buttercream');
foods.push('Chocolate Buttercream');
foods.push('Praline Or Nut Buttercream');
foods.push('Citrus Buttercream');
foods.push('Crème Mousseline (German Buttercream)');
foods.push('Chocolate Ganache');
foods.push('Bittersweet Chocolate Glaze Or Frosting');
foods.push('Milk Chocolate Mocha Glaze Or Frosting');
foods.push('Creamy Decorating Icing');
foods.push('Royal Icing');
foods.push('Quick Cookie Icing');
foods.push('Hard-Sauce Icing');
foods.push('Quick Butterscotch (Penuche) Icing');
foods.push('Quick Chocolate Butter Icing');
foods.push('Quick Brown Butter Icing');
foods.push('Quick Maple Icing');
foods.push('Quick Translucent Sugar Glazes');
foods.push('Honey Bee Glaze For Coffee Cakes');
foods.push('Brûléed Icing');
foods.push('Streusel');
foods.push('Moistening Syrup');
foods.push('Lemon Syrup');
foods.push('Pastry Cream (Crème Pâtissière)');
foods.push('Chocolate Pastry Cream');
foods.push('Coffee Pastry Cream');
foods.push('Mocha Pastry Cream');
foods.push('Banana Pastry Cream');
foods.push('Frangipane Pastry Cream');
foods.push('Butterscotch Pastry Cream');
foods.push('Praline Pastry Cream');
foods.push('Lemon Curd');
foods.push('Lime Or Grapefruit Curd');
foods.push('Orange Curd');
foods.push('Frangipane');
foods.push('Butterscotch Filling');
foods.push('Citrus Custard Filling');
foods.push('Apricot Custard Filling');
foods.push('Chopped Fruit Filling');
foods.push('Toasted Walnut Or Pecan Filling');
foods.push('Almond Or Hazelnut Custard Filling');
foods.push('Coconut-Pecan Filling');
foods.push('Whipped Ganache Filling');
foods.push('Nut Fillings');
foods.push('Apple Filling');
foods.push('Dried Fruit Filling');
foods.push('Poppy Seed Filling Cockaigne');
foods.push('Cheese Fillings');
foods.push('Chocolate Fruit Filling');
foods.push('Fresh Berry Coulis');
foods.push('Mango Coulis');
foods.push('Hot Lemon Or Lime Sauce');
foods.push('Cherry Sauce');
foods.push('Buttered Cider Sauce');
foods.push('Coconut Jam');
foods.push('Crème Anglaise (Custard Sauce)');
foods.push('Vanilla Bean Crème Anglaise');
foods.push('Coffee Crème Anglaise');
foods.push('Chocolate Custard Sauce');
foods.push('Zabaglione');
foods.push('Sabayon With White Wine Or Orange Liqueur');
foods.push('Lemon Sabayon');
foods.push('Chocolate Sauce');
foods.push('Hot Fudge Sauce');
foods.push('Mocha Sauce');
foods.push('Dairy-Free Mocha Sauce');
foods.push('Quick Chocolate Mint Sauce');
foods.push('Chocolate-Caramel Sauce');
foods.push('Chocolate Shell');
foods.push('Salted Caramel Sauce');
foods.push('Caramel Syrup');
foods.push('Butterscotch Sauce');
foods.push('Easy Dulce De Leche');
foods.push('Vanilla Sauce');
foods.push('Marshmallow Sauce');
foods.push('Hard Sauce');
foods.push('Fluffy Hard Sauce');
foods.push('Southern Whiskey Sauce');
foods.push('Hot Brandy Sauce');
foods.push('Hot Brown Sugar Sauce');
foods.push('Orange Liqueur Sauce');
foods.push('Hot Wine Or Plum Pudding Sauce');
foods.push('Hot Buttered Maple Sauce');
foods.push('Baked Custard');
foods.push('Flavorings For Custard Bases');
foods.push('Caramel Custard');
foods.push('Coffee Chocolate Custard');
foods.push('Flan Or Crème Caramel');
foods.push('Flan With Condensed Milk');
foods.push('Vanilla Pots De Crème');
foods.push('Coffee Pots De Crème');
foods.push('Chocolate Pots De Crème');
foods.push('Crème Brûlée');
foods.push('Maple Crème Brûlée');
foods.push('Raspberry Crème Brûlée');
foods.push('Floating Islands');
foods.push('Lemon Or Orange Sponge Custard');
foods.push('Posset');
foods.push('Vanilla Pudding');
foods.push('Butterscotch Pudding');
foods.push('Old-Fashioned Chocolate Pudding');
foods.push('Vegan Chocolate Pudding');
foods.push('Banana Pudding');
foods.push('Banana Pudding With Meringue');
foods.push('Tembleque (Coconut Milk Pudding)');
foods.push('Vanilla Soufflé');
foods.push('Grand Marnier Soufflé');
foods.push('Chocolate Soufflé');
foods.push('Lemon Soufflé');
foods.push('Apricot Soufflé');
foods.push('Sour Cream Apple Soufflé Cake Cockaigne');
foods.push('Additions To Gelatin');
foods.push('Lemon Or Lime Gelatin');
foods.push('Orange Or Grapefruit Gelatin');
foods.push('Fruit Gelatin');
foods.push('Champagne Or Rosé Gelatin With Raspberries');
foods.push('Panna Cotta');
foods.push('Yogurt And Honey Panna Cotta');
foods.push('Chocolate Mousse');
foods.push('Milk Or White Chocolate Mousse');
foods.push('Chocolate Mousse With Gelatin');
foods.push('Rum Chocolate Mousse');
foods.push('Chocolate Terrine');
foods.push('Lemon Or Lime Cold Soufflé Or Bavarian Cream');
foods.push('Orange Cold Soufflé Or Bavarian Cream');
foods.push('Chocolate Or Coffee Bavarian Cream');
foods.push('Bavarian Berry Cream');
foods.push('Charlotte Russe');
foods.push('Chocolate Charlotte');
foods.push('Coffee Charlotte');
foods.push('Tiramisù');
foods.push('Eton Mess');
foods.push('Pavlova');
foods.push('Trifle');
foods.push('Mont Blanc');
foods.push('Baked Rice Pudding');
foods.push('Stovetop Rice Pudding');
foods.push('Rice Pudding Brûlée');
foods.push('Spiced Rice Pudding');
foods.push('Coconut Sticky Rice With Mango');
foods.push('Tapioca Pudding');
foods.push('Baked Pearl Tapioca Pudding');
foods.push('Coconut Tapioca Pudding');
foods.push('Bread Pudding');
foods.push('Chocolate-Banana Bread Pudding');
foods.push('New Orleans Bread Pudding');
foods.push('Baked Fig Pudding');
foods.push('Persimmon Buttermilk Pudding');
foods.push('Pumpkin Buttermilk Pudding');
foods.push('Indian Pudding');
foods.push('Sticky Toffee Pudding');
foods.push('Steamed Chocolate Feather Pudding');
foods.push('Steamed Caramel Pudding');
foods.push('Steamed Plum Pudding');
foods.push('Chocolate Fondue');
foods.push('Coeur À La Crème');
foods.push('Poached Pears In Red Wine');
foods.push('Strawberry Shortcake');
foods.push('Flambéed Fruit');
foods.push('Vanilla Ice Cream');
foods.push('Mint Chocolate Chip Ice Cream');
foods.push('Coffee Ice Cream');
foods.push('Rum Raisin Ice Cream');
foods.push('Tea-Flavored Ice Cream');
foods.push('Matcha Ice Cream');
foods.push('Caramel Ice Cream');
foods.push('Crème Fraîche Ice Cream');
foods.push('Buttermilk Ice Cream');
foods.push('Sweet Cream Ice Cream');
foods.push('Fudge Swirl Ice Cream');
foods.push('Peppermint Stick Ice Cream');
foods.push('Chocolate Ice Cream');
foods.push('Rocky Road Ice Cream');
foods.push('Malted Milk Chocolate Ice Cream');
foods.push('Dark Chocolate Ice Cream');
foods.push('Pistachio Ice Cream');
foods.push('Butter Pecan Ice Cream');
foods.push('Peanut Butter Ice Cream');
foods.push('Coconut Ice Cream');
foods.push('Olive Oil Ice Cream');
foods.push('Spiced Pumpkin Ice Cream');
foods.push('Molasses Ice Cream');
foods.push('Dairy-Free Vanilla Ice Cream');
foods.push('Peach, Apricot, Or Nectarine Ice Cream');
foods.push('Strawberry Ice Cream');
foods.push('Blackberry Or Raspberry Ice Cream');
foods.push('Orange Ice Milk');
foods.push('Pineapple Ice Milk');
foods.push('Chocolate Cups');
foods.push('Hazelnut Gelato');
foods.push('Gianduja Gelato (Chocolate-Hazelnut Gelato)');
foods.push('Fior Di Latte Gelato');
foods.push('Vanilla Frozen Yogurt');
foods.push('Chocolate Frozen Yogurt');
foods.push('Strawberry Frozen Yogurt');
foods.push('Mango Frozen Yogurt');
foods.push('Raspberry Sorbet');
foods.push('Blackberry Sorbet');
foods.push('Blueberry Sorbet');
foods.push('Strawberry Sorbet');
foods.push('Mango Sorbet');
foods.push('Peach Sorbet');
foods.push('Lemon Sorbet');
foods.push('Lime Sorbet');
foods.push('Orange Sorbet');
foods.push('Pink Grapefruit Sorbet');
foods.push('Watermelon Sorbet');
foods.push('Chocolate Sorbet');
foods.push('Champagne Sorbet');
foods.push('Instant Sorbet');
foods.push('Raspberry Or Strawberry Sherbet');
foods.push('Orange Sherbet');
foods.push('Lemon Sherbet');
foods.push('Lime Sherbet');
foods.push('Cranberry Sherbet');
foods.push('Berry Granita');
foods.push('Espresso Or Coffee Granita');
foods.push('Caffè Latte Granita');
foods.push('Citrus Granita');
foods.push('Fruit Ice Pops');
foods.push('Orange Cream Pops');
foods.push('Roasted Banana–Coconut Pops');
foods.push('Chocolate Pudding Pops');
foods.push('Snow Cream');
foods.push('Hot Fudge Sundae');
foods.push('Affogato');
foods.push('Banana Split');
foods.push('Ice Cream Sandwiches');
foods.push('Ice Cream Pie');
foods.push('Frozen Berry Mousse');
foods.push('Coffee Parfait');
foods.push('Hazelnut Semifreddo');
foods.push('Chocolate Semifreddo');
foods.push('Spumoni');
foods.push('Pistachio And Rose Water Kulfi');
foods.push('Baked Alaska');
foods.push('Biscuit Tortonis');
foods.push('Dark Chocolate Truffles');
foods.push('Milk Or White Chocolate Truffles');
foods.push('Vegan Chocolate Truffles');
foods.push('Flavored Ganache');
foods.push('Boozy Chocolate Truffles');
foods.push('Dipped Chocolate Truffles');
foods.push('Coated Chocolate Truffles');
foods.push('Chocolate Bark Or Bars');
foods.push('Chocolate Clusters');
foods.push('Small Solid Chocolates');
foods.push('Filled Chocolates');
foods.push('Peanut Butter Cups');
foods.push('Buckeyes');
foods.push('Joy Of Coconut');
foods.push('Chocolate Fudge');
foods.push('Quick Chocolate Fudge');
foods.push('Penuche (Brown Sugar Fudge)');
foods.push('Jamoncillo De Leche (Mexican Milk Fudge)');
foods.push('Maple Candy');
foods.push('Peanut Butter Or Tahini Fudge');
foods.push('Butterscotch Caramels');
foods.push('Salted Caramels');
foods.push('Chocolate Cream Caramels');
foods.push('Chocolate-Pecan Tortoises');
foods.push('Caramel Corn');
foods.push('Fondant');
foods.push('Quick Fondant');
foods.push('Peppermint Patties');
foods.push('Nougat With Fruit And Nuts');
foods.push('Chocolate Nougat');
foods.push('Divinity');
foods.push('Marshmallows');
foods.push('Salted Caramel Marshmallows');
foods.push('Vanilla Taffy');
foods.push('Chocolate Taffy');
foods.push('Pulled Mints');
foods.push('Peanut Brittle');
foods.push('Megan’S Pumpkin Seed Brittle');
foods.push('Sesame Seed Brittle');
foods.push('English Toffee');
foods.push('Butterscotch');
foods.push('Honeycomb Candy');
foods.push('Coffee Drops');
foods.push('Mexican Orange Candy Cockaigne');
foods.push('Lollipops');
foods.push('Rock Candy');
foods.push('New Orleans–Style Pecan Pralines');
foods.push('French Praline (Praline Powder)');
foods.push('Almond Paste');
foods.push('Marzipan');
foods.push('Sesame Halvah');
foods.push('Gingerbread Halvah');
foods.push('Chocolate Swirl Halvah');
foods.push('Fruit Jellies');
foods.push('Citrus Fruit Jellies');
foods.push('Bourbon Or Rum Balls');
foods.push('Candied Apples');
foods.push('Caramel Apples');
foods.push('Candied Orange Slices');
foods.push('Candied Citrus Peel');
foods.push('Candied Ginger');
foods.push('Crystallized Flowers');
foods.push('Gooseberry Or Currant Jelly');
foods.push('Blackberry Jelly');
foods.push('Grape Jelly');
foods.push('Apple, Crab Apple, Or Quince Jelly');
foods.push('Apple-Bourbon Jelly');
foods.push('Apple-Rose Jelly');
foods.push('Herb Or Scented Jelly');
foods.push('Guava Jelly');
foods.push('Tart Plum Jelly');
foods.push('Rose Hip Jelly');
foods.push('Paradise Jelly');
foods.push('Hot Pepper Jelly');
foods.push('Mint Jelly');
foods.push('Prickly Pear Jelly');
foods.push('Red Red Strawberry Jam');
foods.push('Strawberry Rosé Jam');
foods.push('Berry Jam');
foods.push('Gooseberry Jam');
foods.push('Five-Fruit Jam Cockaigne');
foods.push('Honey-Melon Jam');
foods.push('Fig Jam');
foods.push('Plum Jam');
foods.push('Smoky Tomato Jam');
foods.push('Golden Cherry Tomato And Ginger Jam');
foods.push('Basic Freezer Jam');
foods.push('Apple Butter');
foods.push('Pear Butter');
foods.push('Smoked Apple Butter');
foods.push('Blueberry Butter');
foods.push('Plum Butter');
foods.push('Peach Or Apricot Butter');
foods.push('Jellied Damson Sauce (Damson “Cheese”)');
foods.push('Strawberry Preserves');
foods.push('Apricot, Peach, Or Nectarine Preserves');
foods.push('Strawberry And Rhubarb Preserves');
foods.push('Plum Preserves');
foods.push('Sour Cherry Preserves');
foods.push('Quince Preserves');
foods.push('Peach Or Plum Conserves');
foods.push('Christmas Conserves');
foods.push('Spiced Rhubarb Conserves');
foods.push('Fig And Pistachio Conserves');
foods.push('Sweet Cherry Conserves');
foods.push('Bitter Orange Marmalade');
foods.push('Megan’S Blood Orange Marmalade');
foods.push('Four-Citrus Marmalade');
foods.push('Lime Marmalade');
foods.push('Ginger Marmalade');
foods.push('Dill Pickles');
foods.push('Bread-And-Butter Pickles');
foods.push('Cornichons (Pickled Gherkins)');
foods.push('Chow Chow (Sweet-And-Sour Cabbage Relish)');
foods.push('Tart Corn Relish');
foods.push('Pickled Okra');
foods.push('Pickled Asparagus');
foods.push('Dilly Beans');
foods.push('Pickled Red Or Golden Beets');
foods.push('Lemony Pickled Turnips');
foods.push('Pickled Shiitake Mushrooms');
foods.push('Pickled Peppers');
foods.push('Pickled Garlic');
foods.push('Pickled Garlic Scapes');
foods.push('Pickled Watermelon Rind');
foods.push('Pickled Grapes');
foods.push('Pickled Peaches');
foods.push('Quick-Pickled Vegetables');
foods.push('Quick Sichuan-Style Cucumber Pickles');
foods.push('Pickled Ginger');
foods.push('Pickled Horseradish');
foods.push('Quick-Pickled Onions');
foods.push('Quick Pickled Beets');
foods.push('Jalapeños En Escabeche (Taqueria Pickles)');
foods.push('Pickled Cherries');
foods.push('Tomato Ketchup');
foods.push('Chili Sauce');
foods.push('Mushroom Catsup');
foods.push('Walnut Catsup');
foods.push('Worcestershire Sauce');
foods.push('Curried Apricot Chutney');
foods.push('Apple Or Green Tomato Chutney');
foods.push('Pepperoncini Sott’Olio (Calabrian-Style Chiles)');
foods.push('Salted Egg Yolks');
foods.push('Cured Fish Roe Or Caviar');
foods.push('Home-Cured Bacon');
foods.push('Home-Cured Corned Beef');
foods.push('Pastrami');
foods.push('Sauerkraut');
foods.push('Kimchi');
foods.push('Half-Sour Pickles');
foods.push('Fermented Giardiniera');
foods.push('Salt-Preserved Lemons');
foods.push('Fermented Louisiana-Style Hot Sauce');
foods.push('Kombucha');
foods.push('Tofu Misozuke (Tofu “Cheese”)');
foods.push('Fruit Leather');
foods.push('Jerky');
foods.push('Cherry Bounce');
foods.push('Maraschino Cherries');
foods.push('Rumtopf');
foods.push('Nocino');
foods.push('Acidulated Water');
foods.push('Almond Garnish (Amandine)');
foods.push('Browned Or Buttered Bread Crumbs');
foods.push('Au Gratin');
foods.push('Homemade Sweet Cream Butter');
foods.push('Homemade Cultured Butter');
foods.push('Clarified Butter Or Ghee');
foods.push('Lactic Cheese');
foods.push('Cottage Cheese');
foods.push('Cream Cheese');
foods.push('Ricotta');
foods.push('Basic Pressed Cheese');
foods.push('Feta');
foods.push('Homemade Crème Fraîche');
foods.push('Farofa');
foods.push('Grainy Mustard');
foods.push('Hot Mustard');
foods.push('Ideas For Flavoring Mustard');
foods.push('Nut Butter');
foods.push('Tahini');
foods.push('Nut Or Seed Milk');
foods.push('Infused Oil');
foods.push('Seasoned Salt');
foods.push('Soy Milk');
foods.push('Tofu Or Soybean Curd');
foods.push('Sprouted Seeds');
foods.push('Caramelized Sugar');
foods.push('Flavored Sugars');
foods.push('Tomato Paste');
foods.push('Vanilla Extract');
foods.push('Shallot-Herb Vinegar');
foods.push('Garlic Vinegar');
foods.push('Chile Vinegar');
foods.push('Homemade Yogurt');
foods.push('Yogurt Cheese');

var randFoodItem = foods[Math.floor(Math.random() * foods.length)];
currentItem = randFoodItem;
document.getElementById("card").innerHTML = "<p>"+randFoodItem+"</p>";
}

function acceptCard(){
//alert("Recipe added to grocery list!");
if(!listStarted){
listStarted = true;
document.getElementById("groceryListDiv").setAttribute("style","display:block;");
document.getElementById("metaContainer").setAttribute("style","width:705px;");
}
document.getElementById("groceryList").innerHTML += "<li>" + currentItem + "</li>";
newCard()
}

function startOver(){
listStarted = false
document.getElementById("groceryListDiv").setAttribute("style","display:none;")
document.getElementById("metaContainer").setAttribute("style","width:375px;")
document.getElementById("groceryList").innerHTML = "";
newCard()
}

</script>
<body onLoad="newCard()">
<div style="width:100%;text-align:left;">
<a href="../">Back to other projects</a>
</div><!-- end menu div -->
<div id="metaContainer">
<div id="container">
<div id="header">
<img src="logo.png">
</div><!-- End header-->
<div id="card">
</div><!-- End card -->
<input type="button" value="Skip" id="skip" name="skip" class="button" onClick="newCard()">
<input type="button" value="I'll take it." id="accept" name="accept" class="button" onClick="acceptCard()">

</div><!--End container -->

<div id="groceryListDiv" style="display:none;" overflow="scroll">
<strong>Recipe List</strong><br>
<a style="font-family:'Arial';color:blue;font-size:12px;" href="#">When finished, click here to get shopping list.</a>
<ul id="groceryList">
</ul>
<a style="font-family:'Arial';color:#dddddd;font-size:12px;" href="#" OnClick="startOver()">Click here to start over.</a>
</div><!-- end grocery list div -->

</div><!-- end metaContainer -->

</body>
</html>